- .bazelrc
* Needed to build with clang-10:
In file included from http/get.cpp:3:
In file included from external/asio/_virtual_includes/asio/asio.hpp:111:
In file included from external/asio/_virtual_includes/asio/asio/ip/basic_resolver.hpp:30:
In file included from external/asio/_virtual_includes/asio/asio/ip/basic_resolver_query.hpp:21:
In file included from external/asio/_virtual_includes/asio/asio/ip/resolver_query_base.hpp:19:
external/asio/_virtual_includes/asio/asio/ip/resolver_base.hpp:68:5: error: declaration shadows a variable in namespace 'asio::ip' [-Werror,-Wshadow]
v4_mapped = ASIO_OS_DEF(AI_V4MAPPED),
^
external/asio/_virtual_includes/asio/asio/ip/address_v6.hpp:295:20: note: previous declaration is here
enum v4_mapped_t { v4_mapped };
> Disable -Wshadow in http:get

- dom/dom.h
- style/BUILD
- style/style.cpp
- style/style.h
- style/style_test.cpp
- style/styled_node.h
@zer0-one PTAL. I've invited you to collaborate on this repo. We'll move it to a separate org later.
This handles taking the prepared css rules and applying them to the dom tree, returning an overlay tree where the nodes are decorated with the styles that matched.
I didn't add it in this PR, but this overlay tree should probably prune all branches with `display: none` set.
Next one will be the layout library that will consume the styled tree and use the height/width, padding, and margin attributes to create a skeleton with known positions and sizes for rendering.
> style: Add support for applying a stylesheet to the dom

- CMakeLists.txt
- cmake/Findspdlog.cmake
CMake build fails if distro package does not ship with bundled fmt.
> Use system fmt instead of spdlog bundled version

- browser/BUILD
- browser/gui.cpp
- browser/tui.cpp
- http/BUILD
- http/get.cpp
- http/get.h
This means fewer dependencies in core libraries and that applications
can choose how to handle and display the different errors themselves.
> http: Replace logging with error codes

- layout/BUILD
- layout/layout.cpp
- layout/layout.h
- layout/layout_test.cpp
Right now this only handles the display attribute, but the plan is for
this module to also handle measuring the layout boxes by looking at the
size/padding/margin/border sizes for the elements being displayed.
> layout: Add a new module for creating layout trees

- .bazelrc
- .github/workflows/ci.yaml
Some refactoring of CI steps to install newer versions of clang on Ubuntu.
Added a new build configuration for clang 13 where a couple of warnings are disabled for libpng.
> Add clang 13 to ci

- css/parser.h
- css/parser_test.cpp
Rules for expanding padding :
https://developer.mozilla.org/en-US/docs/Web/CSS/padding
> css: Add support for shorthand property padding

- browser/gui.cpp
- browser/tui.cpp
- css/BUILD
- css/default.cpp
- css/default.css
- css/default.h
- layout/layout.cpp
Previously they always got a width of 0, so there was nothing to render.
This PR also extracts our default CSS into a real .css-file and sets up the correct display values for elements. At first this was the only content I was going to open a PR for, but fixing the display values broke rendering completely since a lot more things became `display: inline`.
> Fix rendering of anonymous blocks and their children

- browser/gui/app.cpp
- geom/geom.h
- geom/geom_test.cpp
- gfx/gfx.cpp
- gfx/gfx.h
This is probably slightly less efficient, but it means we will be able to cull all objects outside of our current viewport if we want.
> gfx: Port scrolling from an opengl translation to translating the painted rects

- browser/gui/app.cpp
This issue was introduced in b39f178426dbcbe40ff744c8628db25b2667068a
where the stored scroll offset was inverted to go with the new IPainter
translation API, but this wasn't taken into account in the mouse
translation calculation.
> browser/gui: Fix mouse document position being incorrect after scrolling

- net/socket.cpp
- net/socket.h
- protocol/http.cpp
- protocol/http.h
- protocol/http_test.cpp
Some refactoring to  parse a http response in steps. The reason for this is to be able to examine the headers before starting to receive and parse the body.
> Receive http response in steps

- html/parser.h
- html2/BUILD
- html2/tokenizer.cpp
- util/BUILD
- util/string.h
- util/string_test.cpp
Moved function for case insensitive string comparison to the util library since I'll need it when comparing header names.
Suggestions for where to place this are welcome!
> Add header for string utility functions

- css/parser.h
std::from_chars is many times faster, doesn't throw, and doesn't depend
on the locale.
This also saves us from having to copy the `std::string_view` into a `std::string` just so `std::stoi` will accept it.
For more information about `std::from_chars` compared to `std::stoi`, see https://www.fluentcpp.com/2018/07/27/how-to-efficiently-convert-a-string-to-an-int-in-c/ and https://stackoverflow.com/questions/55875862/c17-purpose-of-stdfrom-chars-and-stdto-chars
I found this when having issues with valgrind+exceptions when using libc++. :P
> css: Modernize string to int conversion in parser

- .github/workflows/ci.yaml
The clang-12 job was chosen by a fair roll of the dice. :P
Suggestions on what flags or whatever to pass to valgrind are very welcome!
> ci: Update clang-12 to run everything under Valgrind

- util/string.h
- util/string_test.cpp
std::isspace accepts an int, but it's UB to pass anything that's not EOF
or representable as an unsigned char.
See: https://en.cppreference.com/w/cpp/string/byte/isspace
Without the fix, the test added fails in a MSVC debug build (due to an assertion checking that the int passed is within the acceptable range), but appears to pass in all CI jobs even without the fix due to none of them being debug builds.
Here is an example of a failed CI run (with --config debug added): https://github.com/robinlinden/hastur/runs/4204736206?check_suite_focus=true
> util: Fix UB in trim

- browser/engine.cpp
307 is used to redirect e.g. http://startpage.info to https://www.startpage.com
> browser/engine: Follow 307 and 308 redirects

- net/socket.cpp
- net/socket.h
- protocol/http_test.cpp
This PR adds a function for reading a specified number of bytes from a socket. Similar to the other read functions the implementation is quite naive.  Eventually we'll need to add some more logic for handling potential errors and eof.
> Add read_bytes function to socket classes

- .bazelrc
Apparently MSVC already does some of this by default, but no idea which parts, so why not?
See an example failed build here: https://github.com/robinlinden/hastur/actions/runs/1481618257
More info about the libc++ extension here: https://libcxx.llvm.org/UsingLibcxx.html#libc-extensions
> build: Enable libc++ bonus nodiscard additions

- html2/tokenizer.cpp
- html2/tokenizer.h
This is mainly to help me debug when implementing the tree construction for now, but dumping the parse state will be interesting in general later since there will be a ton of things I won't implement until needed.
> html2: Support converting parse tokens into strings

- browser/gui/app.cpp
- gfx/gfx.cpp
- gfx/gfx.h
- render/BUILD
- render/render.cpp
- render/render.h
It felt a bit weird that render had a function that you needed to call
to get the OpenGL painter to work correctly. This still doesn't feel
perfect, but at least now all OpenGL functionality is gathered in one
place.
After this change, gfx only deals with the graphics abstraction and
render only deals with calling into gfx based on what layout nodes it
encounters.
> gfx+render: Move viewport setup from render to gfx

- dom2/character_data.h
- dom2/character_data_test.cpp
- dom2/comment.h
- dom2/comment_test.cpp
- dom2/processing_instruction.h
- dom2/processing_instruction_test.cpp
- dom2/text.h
This implements the CharacterData methods as well as fill out the
simple classes that directly inherit from CharacterData.
I'm not sure what the deal with ProcessingInstruction is. The spec
specifies a member and a getter, but no setter or constructor, so we'll
just have to see how it's used in the rest of the spec when we get there
I suppose.
> dom2: Implement CharacterData and friends

- protocol/BUILD
- protocol/http.h
- protocol/http_test.cpp
Initial support for decoding a chunked body. Still missing support for parsing chunk extensions and trailer part.
Part of #28
> protocol: Add initial support for decoding a chunked body

- browser/engine.cpp
- browser/gui/app.cpp
- dom/BUILD
- dom/dom.cpp
- dom/dom.h
- dom/dom_test.cpp
- html/parser.h
- html/parser_test.cpp
- layout/layout.cpp
- layout/layout_test.cpp
- render/render.cpp
- style/style.cpp
- style/style.h
- style/style_test.cpp
- tui/tui.cpp
This changes it so that Text nodes don't have an always-empty
children member, which means that Node can now be a alias for
std::variant<Element, Text> instead of a type of its own.
I ran into a lot of issues with dom::Node being implicitly constructed
from dom::Element, leading to us returning pointers or references to
temporaries, so the functions I ran into issues with were converted to
use std::reference_wrapper instead of just a plain reference. This means
that it's a compile-time error to pass a temporary.
> Bless dom with a saner node structure

- html2/tokenizer.cpp
The relevant states are:
https://html.spec.whatwg.org/multipage/parsing.html#attribute-value-(double-quoted)-state
https://html.spec.whatwg.org/multipage/parsing.html#after-attribute-value-(quoted)-state
I'm sure more issues like this will pop up once we start using it. Adding all these states gets tedious, so copy-paste errors aren't unlikely. This was found as I was integrating the new parser with the old dom structure and adding tests for it.
> Fix the html2 tokenizer not handling attributes correctly

- html/BUILD
- html/parse.cpp
- html/parser.cpp
- html/parser.h
- html/parser_test.cpp
- html2/tokenizer.cpp
This effectively turns the entire html-library into something that runs
part of the new html2 parser and creates the old dom structure from it.
> html: Replace the ad-hoc parser with a wrapper around the new tokenizer

- util/string.h
- util/string_test.cpp
This commit changes to use string_view in all trim functions. Also made these function constexpr.
> Use string_view in trim functions

- etest/BUILD
- etest/etest.cpp
- etest/etest.h
- etest/etest_main.cpp
- etest/etest_test.cpp
etest_with_main was added because at first I was planning on being fully
compatible with gtest, but I like this more. If a user wants something
like etest_with_main, they can very easily build it on top of etest
themselves.
> etest: Drop support for etest_with_main

- .bazelrc
- third_party/sfml.BUILD
This helps find issues when setting up build files, which is great!
Look at that mess I had made in the SFML build file. :P
> build: Enable the disallow_empty_glob deprecation flag

- css/BUILD
- html2/BUILD
- protocol/BUILD
- util/BUILD
I didn't like that when using the string utils, you also got very unrelated parsing utils, so this commit splits the monolith util target into 1 target per util.
I also played around a bit with Starlark magic in the build file. Not sure if it simplified it or not, but PTAL! It'll need a minor change if we add utils with .cpp-files, but this works as things are right now.
Now instead of depending on `//util`, you depend on `//util:string` or `//util:base_parser`.
> Split up `//util`

- WORKSPACE
v2.5 of imgui-sfml fails when building with NDEBUG defined due to a
variable set but only ever read in an assert.
> deps: Fix release build

- .bazelrc
* See: https://github.com/bazelbuild/bazel/issues/11122
* Using explicit lubsan should be avaided, see:
https://groups.google.com/g/address-sanitizer/c/SD590XDinfQ/m/NMUPj_G0BgAJ
> Use -fsanitize-link-c++-runtime instead of -lubsan

- html2/tokenizer.cpp
- html2/tokenizer_test.cpp
Not sure if `while (true)` is a good idea. My gut feeling tells me that a complete tokenizer never should end up in an eternal loop. Opening PR for discussion.
> Fix so that eof token is emitted from tokenizer

- .github/workflows/ci.yaml
Turns out runners come with Bazel+Bazelisk pre-installed. Wish I'd noticed this before 4e28882722a1b78a06affbc6696cbbe750df77ad, but oh well. I'm sure we can break out other cool things into actions. :P
The Windows 2022 runners left beta a few days ago, so I figured I'd update to those in the same PR, but they're not required for Windows to already have Bazel and Bazelisk pre-installed.
> Clean up CI

- .github/workflows/ci.yaml
- html2/tokenizer.cpp
Also set up the MSVC CI configuration so that it detects this kind of issue.
Example of it detecting the issue fixed in this PR here: https://github.com/robinlinden/hastur/actions/runs/1641134299
> Fix out-of-bounds read in the new HTML tokenizer

- html/parser.cpp
- html/parser_test.cpp
This doesn't add all special cases where this happens, but it sets up
the framework and handles enough of them to render
https://robinlinden.eu/ again! :D
> html: Handle that some elements shouldn't introduce a new scope

- html2/BUILD
- html2/tokenizer.cpp
- html2/tokenizer_test.cpp
- util/unicode.h
- util/unicode_test.cpp
Maybe writing a unicode code point -> utf8 decoder is a bit silly, but it was fun and it has a tiny API, so we can easily replace it with a library in the future if we feel like it.
> Add support for tokenizing non-ascii html entities

- html2/tokenizer.cpp
- html2/tokenizer.h
- html2/tokenizer_test.cpp
- html2/tree_builder.cpp
- html2/tree_builder.h
This PR adds possibility to set the state of the tokenizer. The tree builder will need to be able to set this during processing of tokens. Will be covered by tests when ongoing work on script tag is done.
> Set tokenizer state

- .bazelrc
- WORKSPACE
- browser/BUILD
- gfx/BUILD
- gfx/gfx_example.cpp
- render/BUILD
- style/BUILD
- third_party/sfml.BUILD
This checks that our targets aren't relying on transitive dependencies.
> build: Enable Bazel's layering check

- html2/tokenizer.cpp
- html2/tokenizer.h
- html2/tokenizer_test.cpp
This PR implements all states related to the script tag. Still a todo for emitting replacement character for null.
`TreeBuilder` needs to be updated to set the state of the `Tokenizer` when a `<script>` start tag is encountered.
Part of #139
> html2: Add support for parsing script tag

- html2/tokenizer.cpp
- html2/tokenizer_test.cpp
This PR fixes so that the lowercase version of the input character is appended to the attribute name. Also adds `continue` to break the loop after the character has been appended.
> Fix parsing of uppercase attribute name

- .github/workflows/ci.yaml
Seems like the GH Actions cache is down everywhere right: `https://github.com/actions/cache/issues/698`, but I think should work. Not 100% sure about the Windows cache since the output location is a bit weird, but we'll find out once the cache service is available again.
> ci: Save the Bazel cache across runs

- html/parser.cpp
- html/parser.h
- html2/BUILD
- html2/token.cpp
- html2/token.h
- html2/tokenizer.cpp
- html2/tokenizer.h
- html2/tokenizer_test.cpp
- html2/tree_constructor.cpp
- html2/tree_constructor.h
- html2/tree_constructor_test.cpp
A lot of red commits, but it's because I moved things there's no test coverage on, like the tree constructor and `to_string(Token const &)`.
> html2 cleanup + tree constructor test example

- geom/geom.h
- geom/geom_test.cpp
I've been using this when messing around with Vulkan and OpenGL to clip things to the visible area.
> geom: Add support for getting the intersection of two rectangles

- browser/BUILD
- gfx/BUILD
- gfx/gfx_example.cpp
- gfx/sfml_painter.cpp
- gfx/sfml_painter.h
This can currently only be tested by passing `--sf` to the gfx_example application.
The plan is to hack together a temporary text rendering in this to unblock some other parts we want to work on while I set up more proper text rendering.
> Add an SFML gfx backend

- WORKSPACE
- browser/BUILD
- browser/gui/app.cpp
- browser/gui/app.h
- geom/geom.h
- geom/geom_test.cpp
- gfx/color.h
- gfx/color_test.cpp
The most interesting change is that you can now hit F2 to switch between the SFML and GL rendering backend in the browser GUI.
> Add bits the text rendering depends on

- .bazelrc
- .bazelrc.local.example
- .github/workflows/ci.yaml
Now it'll automatically pass the platform-specific options.
> build: Make --config setup in Bazel more convenient

- layout/layout.cpp
- layout/layout_test.cpp
I need some bits for grabbing properties from the parent node for text rendering, and this is part of being able to test that in a nice way.
> layout: Calculate em sizes based on the current node's font-size

- .github/workflows/ci.yaml
Removing the dependency on `myci-actions/add-deb-repo` actually results in
fewer lines of code without making it less obvious what's going on.
> ci: Simplify setup of newer Clang

- browser/gui/app.cpp
This fixes e.g. clicking in an imgui window also clicking links on the
webpage, and pressing j while entering an url scrolling down.
> browser/gui: Don't handle events already handled by imgui

- protocol/http.h
- protocol/http_test.cpp
This is pretty helpful when debugging. These probably aren't all `InvalidResponse`, but messing around with that seems like a separate issue, and not dropping the status line on the floor is better than nothing. :P
> protocol: Always include the status line when available

- render/BUILD
- render/render.cpp
These may move to //gfx later, but for now they're only needed in //render.
> render: Add support for named colors

- html/parser.cpp
- html/parser_test.cpp
This makes the DOM on https://www.google.com/ look correct. (At a glance. I haven't verified that it's completely correct.)
> html: Switch to the ScriptData state when a script tag is encountered

- .github/workflows/ci.yaml
- .gitignore
- BUILD
- WORKSPACE
With this change, you can generate `compile_commands.json` by running `bazel run refresh_compile_commands` without having to do any setup outside of cloning the repository.
Works fine with gcc and MSVC, but I ran into issues with clang-13.
> build: Make generating compile_commands.json more convenient

- .gitattributes
- html2/BUILD
- html2/test/simple_page.html
- html2/tokenizer_test.cpp
@mkiael Not sure if 005cb7827fc9d827cd15ad5f6a69ad1e57fc6be6 is a good idea. On one hand, I guess our tests would catch any behaviour change, but on the other hand https://en.cppreference.com/w/cpp/language/translation_phases#Phase_5 makes it sound like we shouldn't rely on literals being utf8 at runtime.
Maybe replace the text expected with the hex representation instead to be safe?
> Make sure all tokens are consumed in html2 tests

- gfx/sfml_painter.cpp
This commit makes so that any filesystem_error exception that is thrown from recursive_directory_iterator is catched.
> gfx: Fix crash when font path does not exist

- browser/gui/app.cpp
- browser/gui/app.h
This is temporary, to be reverted once the OpenGL gfx backend handles
everything the SFML one does.
> browser/gui: Default to the SFML gfx backend

- html2/tokenizer_test.cpp
Before this we wouldn't get what line in the test failed, only what line in the expect_{token,error,text} function that was failed.
> html2: Display the correct row:col when token expectations fail

- html2/tokenizer.cpp
- html2/tokenizer.h
- html2/tokenizer_test.cpp
This is in preparation of handling public and system identifiers in the doctype.
> html2: Handle invalid text in doctypes

- layout/layout.cpp
- render/render.cpp
- style/styled_node.cpp
- style/styled_node.h
- style/styled_node_test.cpp
Use std::optional::value_or(fallback) instead.
> style: Get rid of redundant get_property_or function

- html2/tokenizer.cpp
- html2/tokenizer.h
- html2/tokenizer_test.cpp
> html2: Add support for tokenizing the doctype public identifier

- etest/etest.cpp
- etest/etest.h
- style/styled_node_test.cpp
This allows for constructions like
```
for (char quote : std::array{'\'', '"'}) {
test(std::format("thing with {}-quote", quote == '"' ? "double" : "single"), [] { expect(true); });
}
```
> etest: Don't require test names to be kept alive outside of etest

- render/render.cpp
This PR adds initial support for rendering solid borders. This might need to be refactored a bit once we start adding support for more border styles and border radius.
Part #99
> Render solid borders

- html2/tokenizer.cpp
- html2/tokenizer.h
- html2/tokenizer_test.cpp
We still have a few cases where we're emitting the wrong character, but I think this covers all cases where it was missing altogether.
> html2: Add missing replacement-character emits

- .github/workflows/ci.yaml
I sneaked the `--no-install-recommends`-change in as well, but I hope that's fine. :P
> ci: Use cli-stable apt-get instead of apt

- .bazelrc
- third_party/asio.BUILD
We're not using it yet, and since we've gotten quite far without it now
I figure we should make a conscious decision if/when to introduce it
rather than let it sneak in by accident.
> build: Disable rtti

- css/parser.h
- css/parser_test.cpp
This is a fix for that https://github.com was crashing the browser during the CSS parsing.
> css: Fix crash when encountering @keyframes rules

- .github/workflows/ci.yaml
- browser/engine_test.cpp
- etest/etest.cpp
- etest/etest.h
@mkiael Think something like this is fine for now?
I'm hacking on a nicer abstraction that will allow testing this without a live web server to speak with, but this unblocks CI so we can continue merging things. It's been on my todo for a bit, but this makes it more important. :P
> Add support for disabling tests, disable everything accessing live websites in CI

- util/base_parser_test.cpp
Running 100% of the base parser tests at compile time was a fun
experiment, but the tests looking more standard and being able to run
them under Clang as well outweighs the meme-value of it.
> Reduce meme-value of the base-parser tests

- browser/gui/app.cpp
- browser/gui/app.h
With this change, any hovered link will have higher priority than any of its children, so `<a href="http://example.com>text</a>` will now show `a: http://example.com` and be clickable instead of displaying `text` and, well, not be clickable.
> Improve link behaviour

- .github/workflows/ci.yaml
I didn't have to do anything to get it working when adding it, it's
never failed since, and it almost doubles the time it takes our Windows
jobs to run.
The jobs sort of served like documentation for how to use it, but now
that it's added to the README, that's no longer needed.
> ci: Drop compile_command.json checks

- browser/gui/app.cpp
Defaulting to a black background with black text doesn't work great on most websites.
> browser/gui: Render everything against a white background

- gfx/canvas_command_saver.h
- gfx/canvas_command_saver_test.cpp
- gfx/icanvas.h
- gfx/opengl_canvas.h
- gfx/painter.h
- gfx/sfml_canvas.cpp
- gfx/sfml_canvas.h
- render/render.cpp
A struct for grouping border properties is added to make
the draw_border function signature a bit more compact.
Border properties will be extended with radius, style etc.
> gfx: Add struct for grouping border properties

- .bazelrc
- .github/workflows/ci.yaml
We're currently experimenting with C++20's coroutine support, and it
doesn't seem to work with Clang 12. Ubuntu 20.04 is still supported
using GCC 10.
> build: Drop support for Clang 12

- browser/engine.cpp
- browser/engine_test.cpp
- uri/uri.cpp
- uri/uri.h
- uri/uri_test.cpp
> Move uri path normalization from the browser engine to the uri parser

- gfx/sfml_canvas.cpp
- third_party/spdlog.BUILD
This is me dusting off my oldish wip `-fno-exceptions` branch. We can't quite build with it yet, but it's closer.
The main thing remaining is asio, which requires us to provide our own exception handler by defining a template function that's visible everywhere they want to throw.
> Reduce the number of places where we use exceptions

- .github/workflows/ci.yaml
This saves us running CI on every push while still allowing us to manually trigger it on non-PR branches if we want.
> ci: Only run CI for PRs and when manually triggered

- html2/tokenizer_test.cpp
Before this change, the error message would contain the line in the TokenizerOutput that triggered the error.
> html2: Print the line tokenization happened on unconsumed token errors

- html2/tokenizer.cpp
- html2/tokenizer.h
- html2/tokenizer_test.cpp
This adds proper error reporting to all errors paths already unit-tested.
> html2: Update comment tokenizing to emit errors in more places

- .bazelrc
- .github/workflows/ci.yaml
This was done in an attempt to no longer require the user to provide
--config clang/gcc/gcc11/gcc12 when building on Linux, with partial
success. GCC-10 and Clang should now work out-of-the-box without
providing any --config flags.
> build: Make more Linux build flags shared between configs

- os/windows.cpp
This was the only file that used old-style `NULL`.
> os: Replace NULL w/ nullptr

- css/parser.h
- css/parser_test.cpp
- css/rule.h
- dom/dom.h
There is another map with string as the key in `//js`, but that's in `ast.h` which likely is going away in favour of `ast2.h`, so I didn't touch that.
> Don't require heap allocations when doing map<string, T> lookups

- os/linux.cpp
- os/linux_test.cpp
- os/windows.cpp
This patch makes it possible to set the default scale by setting the
environment variable `HST_SCALE`.
> os: Allow overriding the default scale

- browser/gui/app.cpp
- css/rule.cpp
- dom/dom.cpp
- etest/etest.cpp
- html/parser.cpp
- html2/token.cpp
- layout/layout.cpp
- protocol/http.cpp
- protocol/response.cpp
`std::stringstream` has a moving rvalue overload of `str()` since C++20, so let's use that when possible.
> all: Move the string out of stringstreams whenever possible

- html2/BUILD
- html2/tokenizer.cpp
- html2/tree_constructor.cpp
It doesn't really add any value here as we abort in unhandled cases, and
errors are propagated to the caller for them to log if they wish.
> html2: Drop use of spdlog

- html/BUILD
- html/parser.cpp
- html2/tokenizer.cpp
- protocol/response.cpp
- render/BUILD
- render/render.cpp
- util/string.h
- util/string_test.cpp
We had a bunch of issues if the locale wasn't the default `C` one, so I replaced the sort of error-prone `<cctype>` functions with the constexpr versions of them we were already using in `html2`.
> Add locale-independent character helpers to `//util:string`

- browser/BUILD
- browser/gui/app.cpp
- browser/gui/app.h
- util/history.h
- util/history_test.cpp
Currently set to `alt+left` and `alt+right`.
> browser/gui: Add support for simple navigation history

- render/render.cpp
- render/render_test.cpp
Without this patch, we only ignore fully transparent boxes if they also
match the render-internal magical transparent color constant.
> render: Fix fully transparent boxes being rendered

- browser/gui.cpp
- browser/tui.cpp
This patch drops the application name from the log and uses the short
log level instead of the full one.
Before: `[2022-09-04 20:46:20.272] [hastur] [info] Styling dom w/ 14 rules`
After: `[2022-09-04 20:49:10.403] [I] Styling dom w/ 14 rules`
> browser: Shorten the spdlog message boilerplate

- .bazelrc
get_Form_szB: unhandled 35 (DW_FORM_rnglistx)
--9897-- WARNING: Serious error when reading debug info
See: https://bugs.kde.org/show_bug.cgi?id=452758
> build: Work around Valgrind being unable to read Clang 14 debug symbols

- css2/tokenizer.cpp
- css2/tokenizer.h
- css2/tokenizer_test.cpp
Trying out a similar tokenizer for css2 as for html2. Some code duplication here now, but I guess we could make a base class for the tokenizer to reduce it.
Part of #31
> css2: Handle comments during tokenization

- css/parser.h
- css/parser_test.cpp
When working on my other css property work I noticed a website I expected to have a gray background was white even though we support the background-color property. Turns out there's a background shorthand property that a lot of people use.
> Add very partial support for the background shorthand property

- .github/workflows/ci.yaml
If PRs are merged using the web gui merge button, GitHub changes the commit hash even if the PR could be merged by a fast-forward merge, meaning the commit hash we've run CI and sent code coverage info for isn't the same hash as the one on the master branch after the merge.
This commit works around this by also always running CI on commits pushed to master. This will lead to running CI twice on every commit we merge, but at least it doesn't have to be done manually.
> ci: Fix codecov not being updated if PRs are merged via the web gui

- css/BUILD
- css/default.cpp
This was the only part of the browser relying on having a specific working directory or it being started using `bazel run`.
> css: Embed the default css in the css library

- .github/workflows/ci.yaml
Something in the apt.llvm.org repository has changed and now Clang 15 from there no longer works with Bazel.
> ci: Disable broken Clang 15 build

- browser/gui/app.cpp
This helps a bit when debugging layout bits I'm working on.
> browser/gui: Display the cursor position in addition to the hovered node

- .bazelrc
- .bazelrc.local.example
Ubuntu 20.04 only has up to gcc 10, and Ubuntu 22.04 skips past gcc 11 to also support gcc 12, so supporting gcc 11 doesn't really get us anything.
> build: Drop untested gcc11 config

- .bazelrc
- WORKSPACE
- css/BUILD
- css/parser_fuzz_test.cpp
- html2/BUILD
- html2/tokenizer_fuzz_test.cpp
- uri/BUILD
- uri/uri_fuzz_test.cpp
This mostly serves as an example for further work on fuzzing things as the tokenizer is still too incomplete for this to be useful.
Here's what a running it looks like right now:
```
robin@x:~/code/hastur$ CC=clang-14 CXX=clang++14 bazel run html2/tokenizer_fuzz_test_run --config asan-libfuzzer -c dbg
INFO: Analyzed target //html2:tokenizer_fuzz_test_run (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //html2:tokenizer_fuzz_test_run up-to-date:
bazel-bin/html2/tokenizer_fuzz_test_run
INFO: Elapsed time: 0.075s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action
Launching html2/tokenizer_fuzz_test_bin as a libFuzzer fuzz test...
Using test output root: /tmp/fuzzing …
```
> Set up fuzz testing

- .github/workflows/ci.yaml
The bash codecov uploader was apparently deprecated and appears to now have stopped working.
See: https://github.com/codecov/codecov-bash, https://github.com/codecov/uploader
Error when using the old uploader:
```
bash <(curl -s https://codecov.io/bash) -f bazel-out/_coverage/_coverage_report.dat
/dev/fd/63: line 1: no: command not found
```
which makes sense, because that url now points to a page with the content:
```
no healthy upstream
```
> ci: Migrate to the new codecov uploader

- browser/gui/app.cpp
- browser/tui.cpp
- engine/engine.cpp
- engine/engine_test.cpp
- protocol/http_test.cpp
- uri/uri.cpp
- uri/uri.h
- uri/uri_fuzz_test.cpp
- uri/uri_test.cpp
The regex currently in use always matches the input, so we were never failing, but still required the call-site to handle a potential failure.
> uri: Never fail in uri parsing

- css/BUILD
- css/parser.h
- css/parser_test.cpp
With this change we can load github.com again.
> css: Use the keyframes crash workaround for all unhandled at-rules

- .github/workflows/ci.yaml
The preinstalled LLVM was upgraded from 13 to 14 a few months ago, so we don't have to update it ourselves anymore.
This should save us around 1.5 minutes per CI run which is nice since the clang-cl job is the one that takes the longest.
> ci: Use the preinstalled LLVM 14 for the clang-cl job

- WORKSPACE
- dom/BUILD
- dom/dom.cpp
- protocol/BUILD
- protocol/response.cpp
- render/BUILD
- render/render.cpp
- util/BUILD
- util/string.h
In a way this is a bit sad since std::ranges is a lot nicer than what we do right now, but it's also a dependency, and hopefully Clang 16 will finish their range implementation. Even updating to Clang 15 would allow us to use std::ranges for almost all <algorithm> things we do right now.
> Nuke range-v3 dependency

- .github/workflows/ci.yaml
- bzl/defs.bzl
Both shell scripts and .bzl-files were introduced in 774c22cedd1fabbdad0992c4698a6695bf554e3e.
> Enforce more formatting bits in CI

- html2/tokenizer.cpp
- html2/tokenizer_test.cpp
> html2: Fix the replacement character not being emitted in UTF-8

- .github/workflows/ci.yaml
Something in the apt.llvm.org repository has changed and now Clang 15 from there no longer works with Bazel.
> ci: Disable broken Clang 15 builds

- css2/tokenizer.cpp
- css2/tokenizer.h
- css2/tokenizer_test.cpp
Implementation is based on this chapter in the specification: https://www.w3.org/TR/css-syntax-3/#consume-string-token
> css2: Add partial support for tokenizing strings

- .github/workflows/ci.yaml
While not perfect, this does improve the CI run time a lot.
Before:
After:
Resolves #185
> ci: Use the Bazel disk cache in the Windows jobs

- layout/BUILD
- layout/layout.cpp
- layout/layout_test.cpp
The main things being that now we support fractional sizes, and warn on things we don't handle.
> layout: Support fractional sizes in pixel calculation

- .github/workflows/ci.yaml
This is only needed in the Linux jobs, where we don't use --disk_cache and instead save the entire Bazel dir.
> ci: Take the Bazel version into account when computing the cache key

- css2/tokenizer.cpp
- css2/tokenizer.h
This commits adds a function for identifying if a sequnce of character starts an ident sequence. Support for handling escaped characters is still missing.
> css2: Simplify identification of ident sequence

- browser/gui/app.cpp
- engine/engine.cpp
- engine/engine_test.cpp
- uri/BUILD
- uri/uri.cpp
- uri/uri.h
- uri/uri_test.cpp
Previously this was sort of handled in 2 different places in `//engine`, and would have had to be added to yet more places. This also gives us one place to add support for e.g. relative uris which was what I was originally planning on doing.
@mkiael Not sure what to call this member function. `Uri Uri::complete_uri(std::string) const` doesn't feel super intuitive. Any ideas? One thing I considered was adding a `std::optional<Uri> const &base` argument to `Uri::parse`.
> Move handling of origin/scheme-relative uris into `//uri`

- css/parser.h
- protocol/http.cpp
- uri/uri.cpp
- util/string.h
There's no need to calculate the size of the string after the index as the default is to get everything after the index.
Leaving the size out when you want "the rest" makes the intent a bit clearer.
> all: Simplify substr-calls that get the rest of the string

- third_party/fmt.BUILD
- third_party/spdlog.BUILD
No point in ever using the header-only targets now that we've set up the more proper ones.
> deps: Remove unused targets from dependencies

- css/parser.h
- css/parser_test.cpp
We were getting ids like "border-style-top-style" instead of "border-style-top".
> css: Fix border-style parsing creating properties with incorrect ids

- js/ast.h
- js/ast_executor.h
- js/ast_executor_test.cpp
This enables us to expose browser functionality and start writing a JS platform library in a very simple way.
E.g. a very simplified version of [`console.log`](https://developer.mozilla.org/en-US/docs/Web/API/Console/log):
```
std::ostream &log_handle = browser.gui_log_handle();
AstExecutor e;
e.variables["console.log"] = NativeFunction{[&](auto const &args) {
for (auto const &arg : args) { log_handle << arg << '\n'; }
return Value::undefined();
}};
```
> js: Add support for native functions

- render/render.cpp
Moving out of this stringstream was missed when making this change globally as we use an ostringstream instead of a plain stringstream here.
> render: Do less string copying during color parsing

- .bazelrc
- .bazelrc.local.example
- .github/workflows/ci.yaml
- browser/BUILD
- bzl/BUILD
- bzl/copts.bzl
- css/BUILD
- css2/BUILD
- dom/BUILD
- dom2/BUILD
- engine/BUILD
- etest/BUILD
- geom/BUILD
- gfx/BUILD
- html/BUILD
- html2/BUILD
- img/BUILD
- js/BUILD
- layout/BUILD
- net/BUILD
- os/BUILD
- protocol/BUILD
- render/BUILD
- style/BUILD
- tui/BUILD
- uri/BUILD
- util/BUILD
This should make updating 3rd-party deps a bit more convenient at the expense of knowing less about the quality of the libraries we pull in.
> build: Rewamp how we handle warning flags

- browser/gui/app.cpp
I missed committing this change and didn't realize until I tested the browser with all local changes stashed.
> browser/gui: Fix crash on successful imgui-sfml init

- .github/workflows/ci.yaml
I tried to get the Windows jobs working using both `pwd` and `pwd -W`, but I couldn't get it to find the example.html-file, so those will remain a TODO for now.
> ci: Run tui against an example HTML document in Linux jobs

- engine/engine.cpp
Previously, a redirect to something like /sv-se would use /sv-se as the full uri and fail due to the protocol missing.
> engine: Fix following relative redirects

- dom/dom.h
- dom/dom_test.cpp
- layout/layout_test.cpp
We don't want anyone to use this, and we've cleaned it out from everywhere but the dom- and layout tests, so move the helper into the two files where it's used.
> dom: Move dom::Element factory we don't want to less accessible places

- .github/workflows/ci.yaml
GitHub is switching ubuntu-latest to point to 22.04 now, so seems like a decent time to nuke the last few 20.04 jobs we have.
> ci: Update jobs to run on Ubuntu 22.04 instead of 20.04

- WORKSPACE
https://github.com/glennrp/libpng/blob/61bfdb0cb02a6f3a62c929dbc9e832894c0a8df2/CHANGES#L6112-L6122
```
Version 1.6.39 [November 20, 2022]
Changed the error handler of oversized chunks (i.e. larger than
PNG_USER_CHUNK_MALLOC_MAX) from png_chunk_error to png_benign_error.
Fixed a buffer overflow error in contrib/tools/pngfix.
Fixed a memory leak (CVE-2019-6129) in contrib/tools/pngcp.
Disabled the ARM Neon optimizations by default in the CMake file,
following the default behavior of the configure script.
Allowed configure.ac to work with the trunk version of autoconf.
Removed the support for "install" targets from the legacy makefiles;
removed the obsolete makefile.cegcc.
Cleaned up the code and updated the internal documentation.
```
> deps: Update libpng

- render/render.cpp
`transparent` was a special keyword until CSS Level 3 when it was promoted to being a normal color.
> render: Move the transparent color to the correct section

- html2/tokenizer.cpp
- html2/tokenizer.h
- html2/tokenizer_test.cpp
With this change, we can now load msn.com without crashing.
Resolves #207
> html2: Support tokenizing doctype system identifiers

- render/render.cpp
- render/render_test.cpp
I'll add support for providing alpha once I've messed around a bit with our std::from_chars-shim we need for parsing floats using from_chars in GCC 10.
> render: Add support for rgb(1, 2, 3) colors

- css/BUILD
- css/parser.h
- css/parser_test.cpp
This commit breaks cases with comments like like
p /**/ { color: green; }
that previously worked because `p /**/` was processed as two separate selectors with `/**/` being skipped by `skip_whitespace_and_comments`.
> css: Fix selectors w/ spaces being split

- css/parser.h
- css/parser_test.cpp
- css/property_id.cpp
- css/property_id.h
This was the only shorthand property in this list, and dumping any potential single-argument font property values into font-family feels okay for now.
> css: Remove font shorthand from property id list

- html/parser.cpp
This fixes the dom of e.g. https://www.icann.org/en/registry-agreements not being handled correctly during tree-building.
> html: Add missing void elements

- bzl/BUILD
- bzl/copts.bzl
- css/BUILD
- html2/BUILD
- uri/BUILD
No idea why it was set up this way when no other fuzz test was. Past me didn't document it either. :(
> all: Restrict the fuzz tests to only run when using clang

- .gitlint
- url/BUILD
- url/url.cpp
- url/url.h
- url/url_test.cpp
Adds a blob generation function for generating blob URLs according to
the W3C File API spec: https://w3c.github.io/FileAPI/#blob-url-entry
I will follow this PR up with another one that moves the IP serialization functions to util/string.h .
> url: Add url library

- uri/uri.cpp
- uri/uri_test.cpp
Previously, when completing e.g. "bar" with the base "example.com/foo.html", you would end up with the completed uri "example.com/foo.html/bar".
> uri: Fix path-relative completion when the base path doesn't end in /

- browser/gui/app.cpp
- dom/dom.cpp
- dom/dom.h
- dom/dom_test.cpp
- engine/engine.cpp
This adapts our ad-hoc DSL implementation to instead support the abbreviated xpath child axis specifier.
I'll close the xpath issue with this as we're starting down that path instead of using our ad-hoc DSL, and we'll just add to the xpath support as we need it. E.g. I'll probably add support for `//` in the near future as I want to be able to collect all `<a>` tags and all `<img>` tags on a page for the tui and image rendering respectively.
Resolves #219
> dom: Use a subset of xpath instead of an ad-hoc DSL for node-selection

- .github/workflows/ci.yaml
This might be a bit finicky for a bit; will probably require one or two updates in the future as we add different kinds of links in different places and discover that it doesn't match something correctly.
An alternative to this would be to add an explicit tag that I can match on which indicates that a check should be performed. e.g, "[live-check] https://example.com".
> ci: Add a check for link liveness

- .bazelrc
- .clang-tidy
- README.md
- browser/gui/app.cpp
- css/parser.h
- css/parser_test.cpp
Now that we have a few C++23-features in all major compilers, I figure it's time we start playing around with them. :P
I'm working on some style property features that make use of [Monadic operations for `std::optional`](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2021/p0798r8.html), and switching to C++23 feels like something major and separate from upcoming style property PR.
> Target C++23

- .gitlint
- wasm/BUILD
- wasm/leb128.h
- wasm/leb128_test.cpp
This seems to be the number format they decided to use in WebAssembly. I only added support for decoding it into `uint32_t` for now, but it's trivial to update the decoding to be templated on what kind of type you want the leb128-number decoded into.
> wasm: Add support for decoding unsigned leb128 numbers

- browser/gui/app.cpp
ImGui by default will write state to a file in the current working
directory. This is undesirable for a number of reasons. i.a. the
behavior of a gui app shouldn't change when called from a different
directory.
> browser/gui: Support disabling writing to disk

- bzl/copts.bzl
- uri/BUILD
This was missed in 36471c4d5311db7fae836d0325fd1e3325905dd4.
> uri: Nuke leftovers from fuzz-platform cleanup

- protocol/BUILD
- uri/BUILD
- uri/uri.cpp
ctre was causing stack overflows (in protocol/file_handler_test.cpp when using clang-cl).
See:
```
https://github.com/hanickadot/compile-time-regular-expressions/issues/30
https://github.com/hanickadot/compile-time-regular-expressions/issues/209
https://github.com/hanickadot/compile-time-regular-expressions/issues/252
```
I had a quick look at resolving it by removing a few unnecessary capture groups and things like that in our uri-parsing regex (even though it's straight from the RFC, so not ideal), but I was unable to have it both parsing uris correctly and not cause stack overflows when using clang-cl.
> Switch back to std::regex for uri-parsing

- .bazelrc
You can restore the old behaviour by passing --test_summary=short on the command line or adding "test --test_summary=short" to .bazelrc.local.
After:
```
$ bazel test ...
INFO: Invocation ID: ac0d6f92-9904-420c-b414-03a3f56432b6
INFO: Analyzed 111 targets (0 packages loaded, 0 targets configured).
INFO: Found 51 targets and 60 test targets...
INFO: Elapsed time: 0.455s, Critical Path: 0.01s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
Executed 0 out of 60 tests: 58 tests pass and 2 were skipped.
```
Before:
```
$ bazel test ...
INFO: Invocation ID: bfaf239b-761f-4bcc-abb1-6eb2f799dd72
INFO: Analyzed 111 targets (0 packages loaded, 0 targets configured).
INFO: Found 51 targets and 60 test targets...
INFO: Elapsed time: 0.614s, Critical Path: 0.01s
INFO: 1 …
```
> build: Don't print info about cached passed test runs

- codecov.yml
We get this same info from the codecov PR checks anyway, and we can still get to the detailed report by clicking either of codecov's checks.
> ci: Disable codecov comments

- util/BUILD
- util/string.h
- util/uuid.h
This is desirable (but not a hard requirement, for future reference) as the libs under util (especially `//util:string`) are depended on ~everywhere.
We'll switch to std::format and constexpr everything once the compilers we target are a bit more modern, but in neither of these libraries did switching to std::stringstream really decrease readability, so that's nice.
> util: Get rid of third-party dependencies

- html2/tokenizer.cpp
- html2/tokenizer.h
- html2/tokenizer_test.cpp
This is one of the first parts of the tokenizer I wrote, and I guess I didn't add `std::terminate()` where I skipped parts of the spec.
> html2: Handle incorrectly opened comments in tokenizing

- protocol/file_handler_test.cpp
std::rand may not be thread safe, requires the not-great-feeling std::srand setup, and is only guaranteed to produce numbers between 0 and INT16_MAX.
> protocol: Replace std::rand with std::random_device in file handler test

- WORKSPACE
- third_party/icu.BUILD
- url/BUILD
icu will handle IDNA and misc unicode stuff that requires lugging around giant mapping tables that need to stay up-to-date with the unicode standard.
> Add dependency on icu

- net/BUILD
- net/socket.cpp
After this, we're able to connect to and load e.g. https://www.ietf.org/
I had a brief look at esni and ech, but esni isn't a thing in boringssl, and ech is still in-progress. We'll probably be able to get ech working if we put some time into it since it's available behind a flag in Chromium, but that's future work.
SNI: https://www.cloudflare.com/learning/ssl/what-is-sni/
ESNI: https://www.cloudflare.com/learning/ssl/what-is-encrypted-sni/
ECH: https://blog.cloudflare.com/encrypted-client-hello/
> net: Fix ssl handshake failure when SNI is required

- engine/engine.cpp
- engine/engine_test.cpp
This works around us crashing in CSS parsing on https://yahoo.com as we no longer pass one of their gzipped stylesheets to our ad-hoc parser. It should handle any kind of garbage we give to it, really, but we're switching to the spec-compliant css2 soon(tm), so I don't want to spend too much time on it.
> engine: Don't try to parse encoded responses as css

- browser/gui/app.cpp
- layout/layout.cpp
- layout/layout.h
- layout/layout_test.cpp
- render/render.cpp
The only time we ever called get_property on a layout box without a backing style node was in the unit test checking that it doesn't crash.
> layout: Always return a value from LayoutBox::get_property

- .github/workflows/ci.yaml
This cuts down the number of checked URLs by almost half, since so many are the same page with different anchors.
> Dedup URLs for link liveness check

- html2/token_test.cpp
This is mostly so that codecov won't complain at me every time I make a change that touches token.cpp (since it previously had 0% code coverage.)
> html2: Add tests for to_string(Token)

- .bazelrc
- engine/engine_test.cpp
This exercises the multithreading in //engine so tsan can detect any
potential errors.
> engine: Add a test that fetches stylesheets in parallel

- WORKSPACE
- third_party/expected.BUILD
- wasm/BUILD
- wasm/wasm.cpp
- wasm/wasm.h
- wasm/wasm_test.cpp
We'll replace this with std::expected once our compilers have implemented more of C++23.
> deps: Add tl::expected

- wasm/leb128.h
- wasm/leb128_test.cpp
- wasm/wasm.cpp
- wasm/wasm.h
- wasm/wasm_test.cpp
The previous way of parsing value types worked, but it felt sort of gross, so here's a more "proper" implementation. I changed my mind about the hack being cute. :( It kept me up at night.
> //wasm cleanup: Link to the real spec instead of a draft, be less silly when parsing value types.

- layout/layout.cpp
- style/styled_node.cpp
- style/styled_node.h
- style/styled_node_test.cpp
I also added a cute little property-test helper to reduce the dom/style tree boilerplate we need in every test checking properties.
> style: Make border-style properties more strongly typed

- net/BUILD
- net/socket_test.cpp
Maybe this is a bit silly for e.g. `//net` since it's so simple right now, but I guess we'll replace the internals there with std::networking if that happens and then it might be nice to know that a refactoring didn't change anything.
If we like this, we can break it out into a test-lib and use it to test the `//protocol`-bits in a more convenient way.
> net: Set up an in-process http server to test low-level networking bits

- codecov.yml
This isn't really great, but after we migrated from gcc 10 to gcc 11 for code coverage, gcc has been a bit confused about if e.g. functions' closing braces or even lambda variable declarations are covered when it's literally impossible to not hit them if you call the function.
> ci: Allow code coverage to fluctuate a bit

- .github/workflows/ci.yaml
- README.md
- gfx/canvas_command_saver.h
- util/string.h
- util/unicode.h
I finally found that there was a segv hidden in one of the logs when trying to generate the code coverage with gcc 12:
```
bazel-out/k8-fastbuild/testlogs/_coverage/wasm/wasm_test/test/bazel-out/k8-fastbuild/bin/wasm/_objs/wasm/wasm.pic.gcno:version 'B21*', prefer 'B13*'
external/bazel_tools/tools/test/collect_cc_coverage.sh: line 115:    31 Segmentation fault      "${GCOV}" -i $COVERAGE_GCOV_OPTIONS -o "$(dirname ${gcda})" "${gcda}"
```
Seems like Bazel isn't setting GCOV to the version corresponding to the current compiler version in all cases, so I worked around that by setting it to gcov-12 myself.
> Drop support for gcc 11

- .github/workflows/ci.yaml
This allows us to run everything under valgrind again.
> ci: Increase the test timeout when running under valgrind

- .clang-tidy
- browser/gui/app.cpp
- gfx/gfx_example.cpp
- img/img_example.cpp
- protocol/response.h
- util/uuid.h
Initializing our things is essentially free and ensures we'll never have any UB from reading uninitialized types.
C casts try a bunch of different combinations of static_cast, const_cast, and reinterpret_cast, and we want 0 const_casts and our reinterpret_casts visible.
https://clang.llvm.org/extra/clang-tidy/checks/cppcoreguidelines/pro-type-member-init.html
https://clang.llvm.org/extra/clang-tidy/checks/cppcoreguidelines/pro-type-cstyle-cast.html
> Enable more clang-tidy warnings

- .github/workflows/ci.yaml
https://github.com/bazelbuild/buildtools/releases/tag/6.1.0
> ci: Update Buildifier and codecov

- css/default.css
- css/parser.cpp
- css/parser.h
- css/parser_test.cpp
- css/property_id.cpp
- css/property_id.h
- render/render.cpp
- render/render_test.cpp
- style/styled_node.cpp
- style/styled_node.h
- style/styled_node_test.cpp
After this, we support <ins>underlined</ins> and ~strikethrough~ text.
> Add plumbing for, and hook up rendering of text decoration lines

- .github/workflows/ci.yaml
libclang-rt-15-dev appears to be broken in llvm's repo:
dpkg: error processing archive /tmp/apt-dpkg-install-PnMfIE/6-libclang-rt-15-dev_1%3a15.0.7~++20230412114143+8dfdcc7b7bf6-1~exp1~20230412114152.114_amd64.deb (--unpack):
trying to overwrite '/usr/lib/llvm-15/lib/clang/15.0.7/README.txt', which is also in package libclang-common-15-dev 1:15.0.7-0ubuntu0.22.04.1
Seems like libclang-rt-*-dev is no longer needed for linking against ubsan though, so let's drop it.
> ci: Fix clang-ubsan job

- html/parser_states.cpp
- html/parser_states.h
- html/parser_states_test.cpp
Even if we don't yet insert them into the dom, this stops them from
falling through the entirety of the new tree constructor.
> html: Stop comment tokens from falling through to the end of the parser

- browser/gui/app.cpp
- browser/gui/app.h
I would have liked this to be a bool we'd flip when we get an event in
the SFML event loop, but ImGui needs to run for a few iterations every
time it does things.
This reduces idle CPU usage to 0, "busy" CPU usage by a lot, and makes the GUI a lot smoother on displays that can do more than 60 fps.
Resolves #230
> browser/gui: Stop re-rendering the GUI when nothing's happening

- .clang-tidy
- css/parser.cpp
- engine/engine.cpp
- engine/engine_test.cpp
- html2/tokenizer.cpp
- js/ast_executor.h
- util/generator.h
A bunch of false positives in //css where the code could be rewritten to get rid of them, but the plan is to nuke that file altogether once //css2 is more complete, but other than that I think most warnings here were pretty reasonable.
Calling Generator::next() when the generator is done was updated to crash instead of doing whatever UB would happen to do at the time.
> meta: Enable clang-tidy's unchecked-optional-access check

- WORKSPACE
They've deleted everything from their GitHub. Pretty annoying.
> deps: Switch to downloading the xorg deps from their GitLab

- .github/workflows/ci.yaml
- gfx/gfx_example.cpp
- html2/tokenizer.cpp
clang-tidy-15 is needed for the bugprone-unchecked-optional-access check.
This also fixes a few warnings I missed in my last PR. I had them fixed locally and dropped them because I thought clang-tidy could work it out, and it passed CI, so... whoops.
> ci: Update to clang-tidy-15, fix leftover unchecked optional access warnings

- .github/workflows/ci.yaml
Having to scroll past 850 lines of wget progress before I can check why
an upload failed isn't nice.
> ci: Don't print progress when downloading the codecov uploader

- .github/workflows/ci.yaml
The longest time a job has taken so far was 18 minutes and 55 seconds, and that was clang-tidy. Let's kill things that hang after 30 minutes instead of 6 hours. We could definitely have a lower timeout on some of these things, but micromanaging timeouts doesn't seem worth the effort to get notified a few minutes earlier.
See: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idtimeout-minutes
> ci: Decrease the job timeout from 6 hours to 30 minutes

- layout/layout.cpp
- layout/layout.h
- layout/layout_test.cpp
- render/BUILD
- render/render.cpp
This is to enable things like whitespace collapsing, pre-formatting, text-transforms, and text wrapping.
> layout: Add API to get the text a layout box is responsible for

- WORKSPACE
https://think-async.com/Asio/asio-1.28.0/doc/asio/history.html#asio.history.asio_1_28_0
https://github.com/google/boringssl/commit/cbe6df8ae3554efdadd8f2ec1180b28ebdcfd77e
https://github.com/facebookexperimental/libunifex/releases/tag/v.0.0.3
Not sure what's up with unifex being tagged w/ the format `v.0.0.3` instead of `v0.0.3`.
> deps: Update asio, boringssl, and unifex

- layout/BUILD
- layout/layout.cpp
- layout/layout_test.cpp
Previously we were treating all characters as a single line, so 'hi\nhi' was calculated as length(hi) * 2 + length(\n).
> layout: Only use the longest text line's size as the content width

- archive/BUILD
- archive/zlib.cpp
- archive/zlib.h
- archive/zlib_test.cpp
- engine/engine.cpp
- engine/engine_test.cpp
* Error when served zlib as if it were gzip
* Handle `Content-Encoding: deflate`
> engine: Improve Content-Encoding handling

- html2/tokenizer.cpp
- util/unicode.h
- util/unicode_test.cpp
I also yoinked these helpers into util/unicode so I could add some tests without going via the html tokenizer.
> html2: Fix U+1FFF taking U+1FFFE's place as a noncharacter

- .github/workflows/ci.yaml
Bazel no longer seems to work in windows-2022 runners as of version 20230517.1, so we'll drop Windows CI for now.
> ci: Disable Windows jobs to work around broken MSVC setup

- .github/workflows/ci.yaml
- etest/etest.cpp
Running etest without exception support will result in less information for hard test requirements right now.
> etest: Support compiling etest w/ -fno-exceptions

- util/string.h
- util/string_test.cpp
I could've sworn I'd fixed this before, but I guess I either dropped the commit or didn't do it globally or something.
> util/string: Fix ipv6_serialize requiring mutable input

- .bazelrc
`test_env` only affects the `bazel test` command anyway, so let's include it everywhere to keep the analysis cache stuff happy.
See: https://bazel.build/reference/command-line-reference#flag--test_env
After this, the `INFO: Build option --test_env has changed, discarding analysis cache.` prints you get when and after you use `bazel test` to build things.
> build: Fix analysis cache being discarded too often

- WORKSPACE
https://github.com/ocornut/imgui/releases/tag/v1.89.7
https://github.com/gabime/spdlog/releases/tag/v1.12.0
https://github.com/illiliti/libudev-zero/releases/tag/1.0.3
https://github.com/KhronosGroup/Vulkan-Hpp/releases/tag/v1.3.257
> deps: Update imgui, spdlog, udev-zero, and vulkan

- .github/workflows/ci.yaml
Since we switched to running clang-tidy using Bazel, clang-tidy has been
taken from the path, and the default GitHub Actions runner already has a
clang-tidy (as clang-tidy-14) on the $PATH.
> ci: Fix clang-tidy job using the wrong version of clang-tidy

- layout/layout.cpp
- layout/layout.h
- layout/layout_test.cpp
- render/render_test.cpp
This also sets up the infrastructure for me to be able to finish whitespace-collapsing functionality where it would require allocations, e.g. when words are separated by >1 space: `hello     world` should be collapsed to `hello world`.
> layout: Collapse leading whitespace in more places

- url/url.cpp
- url/url_test.cpp
https://url.spec.whatwg.org/#concept-host-parser says that the assert should come after the check for is_not_special, so this change conforms to what the spec wants.
> url: Fix assert() in parse_host w/ empty nonspecial input

- .github/workflows/ci.yaml
The apt.llvm.org packaging issue appears to have been resolved.
> ci: Re-enable libc++ jobs

- third_party/icu.BUILD
- third_party/imgui-sfml.BUILD
- third_party/zlib.BUILD
We don't explicitly enable any warnings in third-party libraries, but that doesn't mean they don't trigger warnings enabled by default.
> deps: Suppress warnings in third-party libraries

- .github/workflows/ci.yaml
https://github.com/prettier/prettier/releases/tag/3.0.2
https://github.com/bazelbuild/buildtools/releases/tag/v6.3.2
> ci: Update buildifier and prettier

- browser/tui/BUILD
- browser/tui/tui.cpp
Previously `bazel run browser:tui -- example.com` would just fail due to the missing scheme.
> browser/tui: Use https if the provided url is missing a scheme

- .clang-tidy
- css/parser_test.cpp
- css/property_id.cpp
- etest/etest.cpp
- gfx/color.cpp
- img/png.cpp
- img/png_test.cpp
- layout/layout.cpp
- os/linux_test.cpp
- style/styled_node.cpp
- url/url.cpp
This adds a bunch of suppressions for where we allocate outside of normal program flow, but I'll remove all of those soon.
> meta: Enable clang-tidy's cert-* checks

- .github/workflows/ci.yaml
https://github.com/bazelbuild/bazelisk/releases/tag/v1.18.0
https://github.com/bazelbuild/buildtools/releases/tag/v6.3.3
> ci: Update Bazelisk and buildifier

- browser/gui/app.cpp
- engine/BUILD
- engine/engine.cpp
- engine/engine.h
- engine/engine_test.cpp
- layout/layout.cpp
- layout/layout.h
This serves two purposes:
1. It allows me to quickly get a sanity check of the whitespace collapsing bits I'm working on.
2. It makes pages readable after collapsing whitespace/newlines in text runs when we still don't have text wrapping.
> layout: Support disabling whitespace collapsing

- css2/tokenizer.cpp
- css2/tokenizer.h
- css2/tokenizer_test.cpp
The end goal of this is that I want to rewrite media-query parsing in terms of the new correct tokenizer and #679. No point in adding to mq-parsing while it's still ad-hoc and this is *so close* to being able to do everything we need to parse them.
> css2: Support parsing integers into number tokens

- css/default.css
- layout/layout_box_test.cpp
- render/render_test.cpp
- style/styled_node.cpp
This matches what other browsers are doing and makes comparing the render results easier.
> Increase the default font-size from 10px to 16px and default links to blue

- .bazelrc
- .bazelrc.local.example
While this probably still works, it's also been unused since the Clang 16 code coverage option was added.
> build: Drop support for Clang 14 code coverage

- .github/workflows/ci.yaml
I was hoping to re-enable this job, but turns out it's broken for a different reason now that Microsoft has updated Clang on the runners.
> ci: Update info about why the clang-cl job is disabled

- .clang-tidy
See: `https://github.com/llvm/llvm-project/issues/57568`, `https://github.com/fmtlib/fmt/issues/3541`.
> meta: Re-enable some clang-tidy warnings we had to disable

- .github/workflows/ci.yaml
It wasn't possible to set this up as a matrix job originally due to gcc-13 missing from the ubuntu-toolchain-r/test ppa.
> ci: Split the gcc-13 job into a matrix job and a noexcept job

- .github/workflows/ci.yaml
We do this by switching to a Bazel release candidate as that's the only option that supports clang-cl-16's include paths.
The timeout for the clang-cl job was also increased a bit as it timed out due to waiting an extra 10 minutes before getting any output from Bazel and the build actually showed any progress.
> ci: Re-enable the clang-cl job

- .bazelrc
- .github/workflows/ci.yaml
This works better than Bazel's `--run_under=qemu-aarch64-static` as it only applies to aarch64 targets and not e.g. shell scripts.
> ci: Run aarch64 binaries using binfmt-misc magic

- browser/gui/app.cpp
- css/default.cpp
- css/default.h
- css/parser.cpp
- css/parser.h
- css/parser_test.cpp
- css/style_sheet.h
- css/style_sheet_test.cpp
- engine/engine.cpp
- engine/engine.h
- engine/engine_test.cpp
- style/style.cpp
- style/style.h
- style/style_test.cpp
This seems like a reasonable thing to do to support things like CSS variables and !important declarations.
> css: Add a style sheet struct

- WORKSPACE
The explicit abseil dependency can now be dropped as it's been updated in rules_fuzzing and no longer requires overriding.
> deps: Update rules_fuzzing

- .github/workflows/ci.yaml
`ci / clang-tidy (pull_request) Successful in 57s` (with cache)
> ci: Add caching to the clang-tidy job

- .github/workflows/ci.yaml
This was already done for all Linux jobs. Not sure why we didn't add it to the Windows ones, but oh well.
> ci: Include the Bazel version in the Windows cache key as well

- wasm/instructions.cpp
- wasm/instructions.h
- wasm/instructions_test.cpp
- wasm/leb128.h
- wasm/wasm.cpp
- wasm/wasm.h
- wasm/wasm_example.cpp
- wasm/wasm_test.cpp
This is enough to get
```
int test(int* input, int length) {
int sum = 0;
for (int i = 0; i < length; ++i) {
sum += input[i];
}
return sum;
}
```
compiled to wasm parsing.
The wat:
```
(module
(type $type0 (func (param i32 i32) (result i32)))
(table 0 anyfunc)
(memory 1)
(export "memory" memory)
(export "_Z4testPii" $func0)
(func $func0 (param $var0 i32) (param $var1 i32) (result i32)
(local $var2 i32) 
i32.const 0
set_local $var2
block $label0
get_local $var1
i32.const 1
i32.lt_s
br_if $label0
loop $label1
get_local $var0
i32.load
get_local $var2
i32.add
set_local $var2
get_local $var0
i32.const 4
i32.add
set_local $var0
get_local $var1
i32.const -1
i32.add
tee_local $var1
br_if $label1
end $label1
end $label0
get_local $var2
)
)
```
> wasm: Add initial instruction parsing

- archive/BUILD
- archive/gzip_fuzz_test.cpp
- archive/zlib.cpp
- archive/zlib.h
- archive/zlib_fuzz_test.cpp
- archive/zlib_test.cpp
```
terminate called after throwing an instance of 'std::logic_error'
what():  basic_string: construction from null is not valid
```
> archive: Fix crash when fed empty input

- engine/engine.cpp
- engine/engine.h
- engine/engine_test.cpp
#740 will be rebased to use `LoadResult Engine::load(Uri)` once this is merged so we don't hand out the protocol-handler and get redirect-handling and stuff for free.
> engine: Follow redirects when loading stylesheets

- css/parser.cpp
- css/parser_test.cpp
- css/rule.cpp
- css/rule.h
- css/rule_test.cpp
- style/style.cpp
- style/style_test.cpp
Not sure this data structure is what we want long-term, but it's trivial to tack on now, and things will probably change quite a bit as we work on and move to the `//css2` parser.
Resolves #362
> css: Handle property-values w/ surrounding whitespace, !important declarations

- style/styled_node.h
- style/styled_node_test.cpp
- util/string.h
- util/string_test.cpp
CSS with quotes around font names, like `font-family: "Arial", serif` was being parsed as `[\"Arial\", serif]` instead of `[Arial, serif]`.
> style: Trim quotes from font-family entries

- .clang-tidy
- .gitlint
- browser/gui/BUILD
- browser/gui/app.h
- engine/BUILD
- engine/engine.cpp
- engine/engine.h
- layout/BUILD
- layout/layout.cpp
- layout/layout.h
- layout/layout_test.cpp
- type/BUILD
- type/naive.h
- type/naive_test.cpp
- type/sfml.cpp
- type/sfml.h
- type/type.h
Previously we were just making a number up (50% of the font-width for the width, 100% for the height.) The making-things-up behaviour is preserved in the `type::NaiveType` `type::IType` implementation as it's useful for tests and things like the tui where we don't care about the measurements.
This currently duplicates some font-search code from `gfx::SfmlCanvas`, but `gfx::SfmlCanvas` should be updated to use the new text/font/typeface system.
> layout: Actually measure the width of text runs

- .bazelrc
This is flipped to enabled by default in Bazel 7 and right now most of our dependencies don't exist in any registry, so let's disable it until we decide we're ready to migrate.
> build: Explicitly disable bzlmod for now

- .github/workflows/ci.yaml
Running these two sanitizers together is fine, so let's do that to save
ourselves a job. This means we're also updating the asan job to use LLVM
15 instead of 14, but that's fine since we still use LLVM 14 for our
tsan tests.
> ci: Combine the asan and ubsan jobs

- browser/gui/app.cpp
- browser/gui/app.h
- browser/gui/gui.cpp
This is useful for e.g. running smoke tests in CI, or profiling single
page loads.
> browser/gui: Add a `--exit-after-load` flag

- third_party/icu.BUILD
This shaves 5-10 minutes off of the GitHub Actions build time for
run_pkgdata_windows.
After: https://github.com/robinlinden/hastur/actions/runs/7175346860
Before: https://github.com/robinlinden/hastur/actions/runs/7066894570
I did add some debug prints to verify that this was the pattern we were getting, so this is just a faster way of finding the same `lib.exe`.
> deps/icu: Be more specific about what lib.exe we're looking for

- .bazelrc
- .github/workflows/ci.yaml
- WORKSPACE
- browser/gui/BUILD
- gfx/BUILD
- img/BUILD
- net/BUILD
- os/BUILD
- third_party/ftxui.BUILD
- third_party/icu.BUILD
- third_party/imgui-sfml.BUILD
- third_party/sfml.BUILD
- third_party/spdlog.BUILD
- third_party/unifex.BUILD
- third_party/zlib.BUILD
- type/BUILD
> ci: Add macos build

- .github/workflows/ci.yaml
I looked into this like half a year and dismissed it due to a lot of weird coverage misses that couldn't happen. Well, now Clang outperforms gcc in spite of those things due to gcc's branch coverage appearing to be pretty broken. Maybe we're missing some flag in gcc to make it produce more accurate coverage, but I didn't see anything obvious.
> ci: Add a Clang 16 code coverage job

- style/styled_node.cpp
- style/styled_node_test.cpp
For all other properties, these keywords are handled by StyledNode::get_raw_property, but font-size is special as it needs to know the node its value originated from.
> style: Fix font-size: {inherit,unset}

- .bazelrc
The kind people over at uber/hermetic_cc_toolchain suggested this as a nicer alternative to my completely switching back to the deprecated behaviour of `sandbox_hermetic_tmp`.
> build: Use a more correct workaround for the slow cross-compile linking

- third_party/BUILD
This is a workaround for the occasional timeouts in the clang-cl job on GH Actions.
> deps: Give the Python requirements.txt-check a more generous timeout

- codecov.yml
We can't really use this to enforce tests being added due to how unreliable the coverage detection has become after the Bazel 7 update.
I'll keep looking into this, but we can't really keep it enabled when it can't even properly detect coverage for boring functions with no branches and keeps randomly flipping coverage for files not touched in a PR between partial and full coverage.
> ci: Switch the code coverage status to informational-only

- .github/workflows/ci.yaml
This should resolve the coverage upload step being flaky.
```
['error'] There was an error running the uploader: Error uploading to
https://codecov.io: Error: There was an error fetching the storage URL
during POST: 404 - {'detail': ErrorDetail(string='Unable to locate build
via Github Actions API. Please upload with the Codecov repository upload
token to resolve issue.', code='not_found')}
```
It should be noted that this secret is only for uploading reports to Codecov and has nothing to do with this repository other than letting Codecov know that the report's from us.
Fixes #797 (probably!)
> ci: Use a Codecov upload token for coverage reporting

- .bazelrc
I tested that the Windows binaries produced by this actually run on Windows. For the macOS configurations, I just checked them w/ `file bazel-bin/util/crc32_test` to make sure that Bazel produced what I expected, but I didn't run any of them.
> build: Add more cross-compilation configurations

- browser/gui/app.cpp
This is helpful when looking back at old logs and trying to work out what page caused what prints. :P
> browser/gui: Log page navigations

- .bazelrc
- .github/workflows/ci.yaml
- browser/BUILD
- browser/gui/BUILD
- gfx/BUILD
- img/BUILD
- third_party/BUILD
- type/BUILD
- url/BUILD
It's now possible to build for aarch64 and friends without manually excluding all targets that can't yet be cross-compiled.
> build: Simplify cross-compilation

- browser/gui/BUILD
- gfx/BUILD
- img/BUILD
- third_party/imgui-sfml.BUILD
- third_party/sfml.BUILD
non_arc_srcs:
```
ERROR: /private/var/tmp/_bazel_runner/62407b805294e85635cf7dcde40ab730/external/sfml/BUILD.bazel:126:13: Compiling src/SFML/Window/OSX/ClipboardImpl.mm failed: (Exit 1): wrapped_clang_pp failed: error executing ObjcCompile command (from target @@sfml//:window_objc) external/local_config_apple_cc/wrapped_clang_pp -target x86_64-apple-macosx13.3 '-stdlib=libc++' '-std=gnu++14' '-D_FORTIFY_SOURCE=1' -fstack-protector -fcolor-diagnostics -Wall -Wthread-safety ... (remaining 53 arguments skipped)
Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
external/sfml/src/SFML/Window/OSX/ClipboardImpl.mm:65:11: error: 'release' is unavailable: not available in automatic reference counting mode
[data release];
^ …
```
> deps/sfml: Fix macOS build, depending on window_macos

- WORKSPACE
- third_party/imgui-sfml.BUILD
- third_party/sfml.BUILD
This broke in 042be7e73fea6d6bcc4990fc367d61c04030e27a when switching to dynamically loading OpenGL w/ glad.
> deps/imgui-sfml: Fix crash due to missing glad-init

- .clang-tidy
Both the check and the docs for the check are removed in clang-tidy-19, so we have to pin this to an older version of the docs until we remove it.
> doc: Fix broken link to deprecated clang-tidy check

- img/BUILD
- img/img_example.cpp
- img/jpeg.cpp
- img/jpeg.h
- img/jpeg_test.cpp
It wasn't easy, but I managed to find and borrow an image from [some openjdk issue](https://bugs.openjdk.org/browse/JDK-8160327) to verify this against.
> img/jpeg: Set up a new library with support for parsing jpeg thumbnails

- style/style.cpp
- style/style.h
- style/style_test.cpp
`:root` is commonly used for declaring global CSS variables:
```css
:root {
--myvar: 13px;
}
```
Part of #189
> style: Support matching the :root psuedo-class

- .bazelrc
- url/url_test.cpp
There is talk in the linked issue about disabling this by default in
Bazel 8, and disabling it appears to bring the benefit of decreasing the
build time in some scenarios due to halving the number of symlinks.
> build: Disable the duplicate 'external' legacy runfiles folder

- css/parser.cpp
- css/parser_test.cpp
f19071b0616694708cb933838fb419e72bd4a159 added some CSS (`text-decoration: dotted underline;`) that our parser wasn't super happy about. This makes it less unhappy.
Part of #19
> css: Better support for expanding the text-decoration shorthand

- css/parser.cpp
- css/rule.h
- url/url.cpp
This can reduce the number of heap allocations made. All stdlibs have some form of small-string-optimization where they can store something like 16-24 characters on the stack before allocating, but always using a string_view where possible doesn't hurt.
One sneaky thing is that maps like `std::map<std::string, Foo>` will require a `std::string` key when indexing into it, possible forcing an allocation for each access. You can work around this by either giving it a transparent comparator like `std::map<std::string, Foo, std::less<>>`, or if the map would have been constexpr if the stdlib allowed it, using string_view as the key instead: `std::map<std::string_view, Foo>`.
> {css,url}: Switch from std::string to std::string_view where possible

- wasm/wasm.cpp
- wasm/wasm.h
- wasm/wasm_example.cpp
- wasm/wasm_test.cpp
This means fewer allocations, earlier failures if something's wrong,
easier error-checking (since if a section fails to parse, the entire
module will now fail to parse), and will allow the module parsing and
validation to be single-pass.
> wasm: Parse module sections eagerly

- wasm/instructions.cpp
- wasm/instructions.h
- wasm/instructions_test.cpp
- wasm/serialize.cpp
- wasm/serialize.h
- wasm/serialize_test.cpp
idk how much uncommitted work you have on this locally, but I figured I'd start hacking away at it. Mainly curious to know what you think about adding that `kMnemonic` constant to the instructions for when we eventually deal with text-format modules.
> wasm: Add instruction serialization with to_string()

- third_party/icu.BUILD
This was printing ~23k lines of warnings in CI.
> deps/icu: Fix warning spam when building w/ clang-cl

- .pre-commit-config.yaml
- third_party/icu.BUILD
@Zer0-One do the icu permalinks point to the right things? I went back a few commits in the history of that file, and it looks like they were pointing to the start of the enum (but I don't understand why) and the pkgdata.inc-comment most of the time.
> ci: Check that all GitHub links are permalinks

- wasm/wasm_example.cpp
The contents of code section entries changed from byte code to parsed instructions in 890c98e487be7218dacbbf264a322e75929ff8a7, but the example wasn't updated to reflect this.
> wasm/example: Fix incorrect code section output

- .github/workflows/ci.yaml
This also updates pre-commit from 2.17.0 to 3.6.2.
> ci: Install pre-commit using pip

- third_party/simdjson.BUILD
- url/url_test.cpp
This makes clangd *a lot* happier hanging out in files including simdjson.
> deps/simdjson: Switch to the not-single-header version

- .github/workflows/ci.yaml
We have no dependencies to the system gl headers after updating SFML to 2.6 and patching imgui-sfml to also use glad.
See: https://github.com/robinlinden/hastur/pull/834, https://github.com/robinlinden/hastur/pull/836
> ci: Drop unnecessary libgl-dev install

- css/parser.cpp
- css/parser.h
- css/parser_test.cpp
This makes https://srctree.gr.ht/repos look like
instead of
Part of #774
> css: Skip over nested CSS instead of letting them break things

- css/property_id.cpp
- css/property_id.h
- css/property_id_test.cpp
- style/styled_node.cpp
At first I was only going to add the color-scheme property, but I didn't like having to touch both //css and //style when doing it.
> css: Yoink the initial property values from //style, add the `color-scheme` property

- WORKSPACE
- html2/BUILD
- html2/html5lib_test.cpp
There are more parts of the test to check, and more tests to include,
but this is a start.
> html2/test: Add an example spec-test from html5lib-tests

- .github/workflows/ci.yaml
This hasn't hit us fully yet since the new runners are still being rolled out, but it's made the Clang 14 job quite flaky.
> ci: Add workaround for Clang 14 on newer GH Actions runners

- .github/workflows/ci.yaml
The clang 15 ubsan/asan and the gcc 12 valgrind jobs both fail due to the entropy change, we were just "lucky" with them getting runners with older kernels until after the last PR was already merged.
> ci: Apply the ASLR+sanitizer workaround to all jobs

- .github/workflows/ci.yaml
We still test clang-17 in the libc++ job.
> ci: Switch the clang-17 libstdc++ job over to clang-18

- css/parser.cpp
- css/parser_test.cpp
These are in use on e.g. https://www.iana.org/help/example-domains and the parser didn't like just running over them.
> css: Parse (and ignore) charset at-rules

- css/default.css
- render/render.cpp
- render/render_test.cpp
We were missing the `display: block` for `<center>`, and we had no CSS at all for `<hr>`. We were also dropping any elements that had either height or width == 0, even if a border size would cause things to be rendered anyway.
We're still not centering things inside of the `<center>` element, but that's a future someone's problem.
Before:
After:
> Improve rendering of the nginx default error pages

- browser/gui/app.cpp
SFML defaults to interpreting string bytes as having the locale the current system does. This doesn't work for us as we treat everything as UTF-8 internally, and most of the web uses UTF-8.
> browser/gui: Always show page titles as UTF-8

- css/property_id.cpp
- css/property_id.h
- style/styled_node.cpp
- style/styled_node.h
- style/styled_node_test.cpp
All inline-ish display values should be mapped to block-ish in the presence of a float value that is not none.
This fixes the content on https://00f.net/2023/01/04/webassembly-benchmark-2023/ not being visible.
> style: Handle weird display and float css property interactions

- style/style.cpp
- style/style_test.cpp
- style/styled_node.cpp
- style/styled_node.h
- style/styled_node_test.cpp
This fixes a lot of things on https://eatonphil.com, a blog I found browsing https://lobste.rs/ in hastur.
Part of  #189
> style: Support lookup of inherited css variables

- .github/workflows/ci.yaml
- bzl/BUILD
- bzl/copts.bzl
I broke this in https://github.com/robinlinden/hastur/commit/9e3b54318b6f7a7547183e942a72e3a8ef95bbb4, and since we don't explicitly run any fuzz tests in CI, they were just quietly disabled.
This fixes the fuzz testing platform selection and explicitly runs a fuzz test in CI to make sure this can't happen again.
> build: Fix broken fuzz test platform selection

- idna/idna_data_processor.py
- idna/uts46_test.cpp
The \u1234 escapes only work with exactly 4 characters.
> idna: Fix uts46 mappings to code points >0xFFFF being broken

- WORKSPACE
- idna/BUILD
- idna/unicode.cpp
- idna/unicode.h
- idna/unicode_data_processor.py
- idna/unicode_test.cpp
This is needed for the NFC normalization we have to perform when doing the UTS46 processing.
> idna: Process ucd code point decomposition data into a C++ish table

- html/parser_test.cpp
This mostly adds tests for error-handling, but also things like comments and doctypes.
> html: Improve test coverage

- css/media_query.h
- css/media_query_test.cpp
With some [additional fixes](https://github.com/robinlinden/hastur/pull/945) in `//style` to deal with `.class1.class2` selectors, this makes the
```html
<head>
<style>
.theme-a {
background: #dca;
color: #731;
}
@media (prefers-color-scheme: dark) {
.theme-a.adaptive {
background: #753;
color: #dcb;
outline: 5px dashed #000;
}
}
.theme-b {
background: #447;
color: #bbd;
}
@media (prefers-color-scheme: light) {
.theme-b.adaptive {
background: #bcd;
color: #334;
outline: 5px dotted #000;
}
}
</style>
</head>
<body>
<div class="box theme-a">Theme A (initial)</div>
<div class="box theme-a adaptive">Theme A (changed if dark preferred)</div>
<br />
<div class="box theme-b">Theme B (initial)</div>
<div class="box theme-b adaptive">Theme B (changed if light preferred)</div>
</body>
```
example …
> css: Implement prefers-color-scheme media queries

- css/media_query.h
- css/media_query_test.cpp
These are in use on e.g. https://seirdy.one/
Before:
After:
> css: Support media-type media queries

- browser/gui/app.cpp
- browser/gui/app.h
- engine/BUILD
- engine/engine.cpp
- engine/engine.h
- engine/engine_test.cpp
- protocol/BUILD
- protocol/file_handler.cpp
- protocol/file_handler.h
- protocol/file_handler_test.cpp
- protocol/http.h
- protocol/http_handler.cpp
- protocol/http_handler.h
- protocol/http_test.cpp
- protocol/https_handler.cpp
- protocol/https_handler.h
- protocol/iprotocol_handler.h
- protocol/multi_protocol_handler.h
- protocol/multi_protocol_handler_test.cpp
- protocol/response.cpp
- protocol/response.h
- protocol/response_test.cpp
Previously, we'd return a `Reponse` w/ `ErrorCode::Ok` for success and a `Response` w/ a non-`Ok` error code and no headers or body for an error. Now `Response` has no error code, and we have a separate `Error` struct with only an error code and an optional status line, which was what you really got in the error case before.
> protocol: Split success and error results into separate types

- browser/gui/app.cpp
We were accessing error() of a tl::expected when downloading the favicon worked but SFML failed to load it as an image.
Introduced in 7622d7444a095980cad794658e5b888ceeacdb58.
> browser/gui: Fix crash on favicon image data load failure

- .github/workflows/ci.yaml
Before:
```
Spider mode enabled. Check if remote file exists.
--2024-05-13 23:26:46--  https://bazel.build/
Resolving bazel.build (bazel.build)... 216.58.211.14, 2a00:1450:400f:803::200e
Connecting to bazel.build (bazel.build)|216.58.211.14|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 77416 (76K) [text/html]
Remote file exists and could contain further links,
but recursion is disabled -- not retrieving.
Spider mode enabled. Check if remote file exists.
--2024-05-13 23:26:47--  https://broken-link.robinlinden.eu/
Resolving broken-link.robinlinden.eu (broken-link.robinlinden.eu)... failed: Name or service not known.
wget: unable to resolve host address ‘broken-link.robinlinden.eu’
```
After:
```
2024-05-13 23:26:55 URL: https://bazel.build/ 200 OK
wget: unable …
```
> ci: Make the link-liveness job output easier to skim

- .github/workflows/ci.yaml
The stack traces when something goes wrong in these jobs isn't informative enough to be very useful.
> ci: Use debug builds in valgrind/asan/tsan jobs

- .github/workflows/ci.yaml
- browser/gui/app.cpp
- url/url_test.cpp
Looks like 18 is better at west vs east const and deals with indentation differently somehow.
> ci: Update to clang-format 18

- .github/workflows/ci.yaml
We no longer support Clang 15 and older, and GitHub has stopped installing the incompatible libstdc++.
> ci: Drop no-longer-needed workaround for Clang+libstdc++-incompatibility

- browser/gui/app.cpp
- browser/gui/app.h
- engine/engine.cpp
- engine/engine.h
- engine/engine_test.cpp
- os/BUILD
- os/memory_windows.cpp
- os/system_info.h
- os/system_info_linux.cpp
- os/system_info_linux_test.cpp
- os/system_info_windows.cpp
- os/xdg_windows.cpp
The default is light mode, but you can force it to dark mode by setting the `HST_DARK_MODE` env var to `1`.
Working out if the user wants dark mode or not on Linux is a bunch of work, so that's a todo for someone in the future.
> Calculate prefers-color-scheme media queries based on the OS dark mode preference

- html2/parser_states.cpp
- html2/parser_states_test.cpp
This may introduce bugs because it's even more mixing of the old and new parser, but let's deal with those bugs when we hit them and keep working towards dropping the old parser.
> html2: Create the body element in AfterHead if needed

- .github/workflows/ci.yaml
This should fix the token issues in PRs from forks.
> ci: Pass the codecov token using an env var

- third_party/fmt.BUILD
- third_party/zlib.BUILD
Before (wasi-wasm CI job):
`Executed 38 out of 110 tests: 38 tests pass and 72 were skipped.`
After (wasi-wasm CI job):
`Executed 43 out of 110 tests: 43 tests pass and 67 were skipped.`
> deps: Support wasm cross-compilation for more targets

- archive/BUILD
- engine/BUILD
This both makes the coverage feedback in fuzzing nicer, and allows things like the GIF image parser to only depend on lzw without also pulling in gzip/zlib-handling.
> archive: Split into one target per archive format

- css/property_id.cpp
- layout/BUILD
- layout/layout.cpp
- layout/layout_test.cpp
- style/styled_node.cpp
- style/styled_node.h
- style/styled_node_test.cpp
This gives the `xn--[...]` labels on https://www.iana.org/domains/reserved the correct capitalization.
>  layout: Apply text-transform transforms 

- .github/workflows/ci.yaml
@Zer0-One this should hopefully unbreak the coverage jobs.
> ci: Work around coverage report uploads failing in PRs from forks

- util/variant.h
- util/variant_test.cpp
- wasm/BUILD
- wasm/instructions.cpp
- wasm/instructions.h
- wasm/instructions_test.cpp
- wasm/serialize.cpp
- wasm/serialize_test.cpp
- wasm/validation.cpp
- wasm/validation.h
- wasm/validation_test.cpp
This validation code assumes we're doing a separate validation pass, and not validating as we parse.
> wasm: Add module validation

- html/BUILD
- html/parser.cpp
- layout/layout.cpp
- layout/layout_test.cpp
The spec-compliant html parser in #994 emits whitespace nodes even if they're all whitespace, and that wasn't handled in the layout system as our old ad-hoc html parser dropped all whitespace-only nodes. Now it's handled in the layout system, and we can remove that hack from our ad-hoc parser.
This fixes a lot of minor whitespace issues on a lot of websites. E.g.
turns into
with this fix.
> layout: Drop completely empty text nodes

- archive/gzip_fuzz_test.cpp
- archive/zlib.cpp
- archive/zlib.h
- archive/zlib_fuzz_test.cpp
- archive/zlib_test.cpp
- archive/zstd.cpp
- archive/zstd.h
- archive/zstd_fuzz_test.cpp
- archive/zstd_test.cpp
- engine/engine.cpp
std::byte is like the char types in that it's allowed to alias anything.
std::uint8_t doesn't have this magic, so when using it we also have to
static_assert that it's an alias of one of the blessed character types
that can alias anything.
The zlib-decoding used char types, so it didn't have this issue, but it
was also updated for consistency.
> archive: Use `std::byte` as the input type in the API

- layout/layout.cpp
- layout/layout_box.cpp
- layout/layout_box.h
- layout/layout_box_test.cpp
- layout/layout_test.cpp
- render/render.cpp
- render/render_test.cpp
- style/styled_node.cpp
- style/styled_node_test.cpp
- tui/BUILD
- tui/tui.cpp
A LayoutBox is an anonymous block if LayoutBox::node == nullptr, and a box being a block or an inline node is known in the StyledNode.
> layout: Remove unnecessary LayoutBox::type member

- layout/box_model_test.cpp
- layout/layout.cpp
- layout/layout_box.cpp
- layout/layout_box.h
- layout/layout_box_test.cpp
- layout/layout_property_test.cpp
- layout/layout_test.cpp
- layout/unresolved_value.cpp
- layout/unresolved_value.h
- layout/unresolved_value_test.cpp
This matches what other browsers do, but they also do it for all properties. These two were resulting in culling not rendering anything, so more important than other properties. I'll set something more general for this later.
Note that invalid in our case often is things like unsupported units or calc()'d values, so logging the values we couldn't resolve is still useful until we support more things.
> layout: Treat invalid width properties as 'auto'

- WORKSPACE
There is a 0.34.0 of `rules_python`, but they removed the `entry_point`-macro we use for glad, and following the [migration instructions](https://github.com/bazelbuild/rules_python/blob/0.33.2/python/private/bzlmod/requirements.bzl.tmpl#L28-L46) has their generated script-wrapper exploding on being unable to import the main entry point, so I'll look into that later.
> deps: Update rules_python, fmt, simdjson, and wpt

- WORKSPACE
The sha256 checksum of the tag changed, so I guess we shouldn't count on tags being stable in that repo.
> deps/wpt: Point to a commit in master instead of a tag

- WORKSPACE
The checksum of the wpt-commit fetched changed as well.
See: d6271fd31b44a81ede755521a5143dc57565bbac
~This feels super dodgy, and it's only affecting the wpt repo.~ Not dodgy, just `.git_archival.txt`-magic. This is fine as a workaround.
> deps/wpt: Fetch using git_repository instead of http_archive

- .github/workflows/ci.yaml
As our full rebuild time is low, and the parts of the cache we can use after a cache miss is likely pretty low, let's save on cache disk space by not including any possibly-useless old cache bits.
> ci: Don't restore old caches after a miss

- etest/etest2.cpp
`std::cout` is buffered, so if the test body hits e.g. an assert, it's likely that the crashing test's name won't show up in the output.
Before:
```
good test : PASSED
Assertion failed: false, file etest/meme_test.cpp, line 5
```
After:
```
good test : PASSED
bad test  : Assertion failed: false, file etest/meme_test.cpp, line 5
```
> etest: Print the test name even if the test crashes

- css/parser.cpp
- css/parser_test.cpp
Without this, any `@import` at-rules are likely to kill parsing of the rest of the document.
---
This makes https://owickstrom.github.io/the-monospace-web/ look like
instead of
, so while it's still broken, it's a lot better.
> css: Ignore `@import` at-rules

- style/styled_node.cpp
This means that the data is a compile-time constant instead of
heap-allocated at runtime, so no allocations and no nolints.
> style: Replace small maps w/ array<pair>

- .clang-tidy
- css/parser.cpp
- dom/dom.cpp
- html2/parser_states.cpp
- layout/layout.cpp
- layout/layout_box.cpp
- layout/layout_box.h
- layout/layout_box_test.cpp
- layout/layout_test.cpp
- render/render.cpp
- style/style.cpp
- style/styled_node.cpp
- style/styled_node.h
- tui/tui.cpp
- unicode/normalization.cpp
- uri/uri.cpp
- url/url.cpp
- wasm/byte_code_parser.cpp
Most of these places need some form of recursion depth restriction or rewriting.
> meta: Enable clang-tidy's misc-no-recursion lint

- .bazelrc
Ubuntu 24.04 ships Valgrind 3.22 which is newer than the 3.19 version needed for DWARF-5 to work.
> build: Drop no-longer-needed fix for old Valgrind

- layout/layout.cpp
We were already resolving this to 0, but with a warning due to `auto` not being parseable as a number.
This gets rid of a few warnings on https://gr.ht.
> layout: Explicitly resolve margin-{top,bottom}: auto to 0

- uri/uri.cpp
- uri/uri_test.cpp
E.g. base=example.com, url=#test => example.com#test
> uri: Support completing fragments

- codecov.yml
Looks like something shifted in codecov or the compilers we use as the project code coverage jumped 3% the other day and has stopped randomly fluctuating, meaning this should be fine again.
#1043 looks like the first PR where the code coverage was back to what we should expect.
> ci: Make the code coverage status required again

- .github/workflows/ci.yaml
This is possible now that we're on SFML 3.
> ci: Use libc++-19 in the clang-tidy job

- css2/BUILD
- css2/token.h
- css2/token_test.cpp
- css2/tokenizer.cpp
- css2/tokenizer.h
- css2/tokenizer_test.cpp
- util/from_chars.h
- util/from_chars_test.cpp
There's still no support for things like `.25`, `-.25`, or `+.25`, but I'll set that up soon.
> css2: Support tokenizing floating point numbers

- etest/etest2.cpp
- etest/etest2.h
- etest/shuffled_tests_test.cpp
We don't want dependencies between tests.
This finds the `errno` issue in `util::from_chars` resolved in #1054:
```
$ bazel test ... --runs_per_test=10
<...>
//util:from_chars_test  FAILED in 7 out of 10 in 0.2s
```
> etest: Run tests in a randomized order

- codecov.yml
Guess things have shifted again somehow.
This reverts commit 8138d925fca44b83f4b5b34dd4c38b4a8b41f06c.
I'm mildly annoyed. :(
> ci: Make the code coverage status informational again

- html2/parser_states.cpp
- html2/parser_states_test.cpp
There are a bunch of elements that InBody handles using InHead's rules
and all of them need to be handled as <head> won't be the topmost
element when this happens.
This makes arstechnica.com once again make a dom tree even if you're running in debug mode.
> html2: Fix assertion failure when parsing <body><template>

- .github/workflows/ci.yaml
- README.md
- html2/BUILD
- html2/token.cpp
- html2/tokenizer_test.cpp
- protocol/BUILD
- protocol/file_handler_test.cpp
- protocol/http.cpp
- uri/BUILD
- uri/uri.cpp
This drops gcc 12, Clang w/ lib++ 16, and whatever GitHub's macOS 13
runner uses.
The gcc 14 job was switched over to run tests under valgrind to cover
what gcc 12 was previously doing.
> ci: Drop support for setups that don't support std::format

- browser/gui/app.cpp
- browser/tui/BUILD
- browser/tui/tui.cpp
- css/BUILD
- css/parser.cpp
- css/parser_test.cpp
- css/property_id_test.cpp
- style/BUILD
- style/style_test.cpp
- third_party/spdlog.BUILD
`fmt::join` was left in a few places as there's no good well-supported
alternative in the stdlib yet, and we're still depending on fmtlib via
spdlog anyway.
> Replace all fmt::format-bits w/ std::format

- css2/BUILD
- css2/token.h
- css2/tokenizer.cpp
- css2/tokenizer.h
- css2/tokenizer_fuzz_test.cpp
- css2/tokenizer_test.cpp
The consume_number code has become quite janky and should be updated to more closely match the spec, but this fixes all issues fuzzing found.
> css2: Fix assertion failures and set up fuzz testing

- os/memory.h
- os/memory_linux.cpp
- os/memory_windows.cpp
```
// Starting w/ LLVM 17, ubsan will read 8 bytes before the start of functions,
// so we have to add a few hacks to allocate extra memory and offset pointers to
// work around this undocumented(?) change.
//
// See:
// * https://github.com/llvm/llvm-project/issues/65253
// * https://github.com/llvm/llvm-project/commit/ad31a2dcadfcd57a99bbd6d0050d2690fd84a883
```
> os/memory: Work around ubsan doing weird things

- .bazelrc
This was incorrectly written as detect_odr_violation*s*, and there's no warning about unhandled arguments unless you turn up the verbosity of asan:
```
WARNING: found 1 unrecognized flag(s):
detect_odr_violations
```
See: https://github.com/google/sanitizers/wiki/AddressSanitizerOneDefinitionRuleViolation
> build: Fix detect_odr_violation not being enabled

- etest/etest2.h
- idna/punycode_test.cpp
These tests are both evaluated in static-asserts and run like normal
tests in order to allow measuring code coverage and things like that.
> etest: Add support for compile-time tests

- .bazelrc
- .github/workflows/ci.yaml
This also means we're now testing Clang 19 w/ libstdc++. Clang 18 w/
libstdc++ is still tested in the various sanitizer jobs, so no need for
an additional job for that.
> ci: Update the Clang coverage job to Clang 19

- WORKSPACE
Updating this was missed in d5194a34a2165afe38b2fce0af2596465e383a60.
> deps/boringssl: Add missing sha256

- style/style.cpp
- style/style_test.cpp
This adds support for things like [a][b=c], but no exotic forms of
matching, and also not things like asdf[foo=bar] where the attribute
isn't relatively alone.
Resolves #943
> style: Support parts of attribute matching

- css/parser.cpp
- css/parser_test.cpp
This improves e.g. https://www.iana.org/help/example-domains and https://srctree.gr.ht/repos
iana by correctly skipping over IE hacks, and grht by making the nested rule detection better.
> css: Fix IE hacks being parsed as nested rules

- README.md
- WORKSPACE
Generating compile commands for Linux is still pretty broken due to
missing support for the parse_headers-feature some of our dependencies
use, but I'll look into that more later.
Also, trying to generate compile commands w/o forcing system_python bootstrapping fails w/:
```
$ bazel run refresh_compile_commands
INFO: Invocation ID: f85c2e11-6972-4caa-8e54-161a9275d097
INFO: Analyzed target //:refresh_compile_commands (61 packages loaded, 3436 targets configured).
INFO: Found 1 target...
Target //:refresh_compile_commands up-to-date:
bazel-bin/refresh_compile_commands.zip
bazel-bin/refresh_compile_commands.exe
bazel-bin/refresh_compile_commands.check_python_version.py
bazel-bin/refresh_compile_commands.py
INFO: Elapsed time: 7.820s, Critical Path: 4.05s
INFO: 4 processes: 3 internal, 1 …
```
> Fix compile command generation on Windows

- .github/workflows/ci.yaml
This means the oldest macOS toolchain we test with now is whatever Xcode 16 provides, so we get access to 'Parenthesized initialization of aggregates' (p0960) and can use things like emplace_back and make_unique w/ our structs w/o having to add c-tors to them.
> ci: Drop the macos-14 job

- css/media_query.h
- css/media_query_test.cpp
Technically, 'only' means "only applies if the entire query matches", but that's also the only way we interpret queries right now.
> css: Support the 'only {all,print,screen}' media type syntax

- .clang-tidy
- css/parser.cpp
- js/tokenizer_test.cpp
- layout/layout_property_test.cpp
- layout/layout_test.cpp
- render/render_test.cpp
- style/style.cpp
- style/styled_node_test.cpp
- url/url.cpp
- wasm/validation.cpp
These were previously blocked by Xcode 15 and older not implementing p0960.
> Enable more of clang-tidy's modernize checks

- type/sfml.cpp
Caching lookup failures is good because otherwise we will look at all fonts available every time someone requests the unavailable font, likely multiple times during every render.
This improves the performance of pages where the first font in the font-family property isn't available by several orders of magnitude.
> type/sfml: Fix cache never considering lookup failures to be cached

- etest/etest2.cpp
- etest/etest2.h
Splitting out requirement_failure and expectation_failure in this way allows us to simplify the actions inheriting from IActions, conveys more information to the compiler (using noreturn), and allows us to drop a nolint.
The [[noreturn]] thing is extra nice as now compilers can know that e.g.
```
a.require_eq(some_vec.empty(), false);
a.expect_eq(some_vec[0], 42);
```
will never access some_vec[0] if some_vec is empty.
> etest: Simplify IActions

- .github/scripts/check_url_liveness
- .github/workflows/ci.yaml
I guess the (new?) cloudflare stuff makes our spidering unhappy. I'll check this locally every now and then. It's not that often that things go down for reasons that require us to do something about it.
> ci: Move the link-liveness check into a script

- .github/workflows/ci.yaml
The Windows jobs are happier and run in max ~18 minutes after 7650574, while clang-tidy has slowly gotten slower over time, and can now take >30 minutes sometimes.
> ci: Update timeouts to better match reality

- style/styled_node.cpp
- style/styled_node_test.cpp
This makes the colors on Swedish news website https://svt.se work:
Before:
After:
> style: Support resolving variables pointing to variables

- WORKSPACE
This probably broke when we updated Bazel at some point, and it's yet to be fixed in upstream.
> meta: Fix Linux compile command generation

- gfx/color.cpp
- url/url.cpp
Same reason as in earlier [PRs](https://github.com/robinlinden/hastur/pull/1035).
This means that the data is a compile-time constant instead of
heap-allocated at runtime, so no allocations and no nolints.
After this and #1108, we have no cert-err58 nolints left.
> Replace small maps w/ array<pair>

- html2/parser_states.cpp
- html2/parser_states_test.cpp
This brings http://info.cern.ch/hypertext/WWW/History.html from
to
> html2: Handle dd & dt start tags

- layout/layout.cpp
- layout/layout_box_test.cpp
- layout/layout_test.cpp
This makes them behave more like regular blocks which is extra nice when websites do things like place blocks inside inlines.
> layout: Give anonymous blocks the width of their parent

- WORKSPACE
- html2/BUILD
The native rule is being removed in favour of rules_shell in Bazel 8.
> deps: Use rules_shell instead of the native sh_test rule

- gfx/font.h
- render/BUILD
- render/render.cpp
- render/render_test.cpp
- style/styled_node.cpp
- style/styled_node.h
- style/styled_node_test.cpp
This does nothing in e.g. Firefox as well.
> style: Drop support for text-decoration: blink

- bzl/defs.bzl
Things like this will become errors in Bazel 9.
> build: Clean up forgotten native sh_test rule

- .bazelrc
- .github/workflows/ci.yaml
- MODULE.bazel
- WORKSPACE
This only adds the dependencies that are required for Bazel to be happy
with not being able to access a bzlmod registry, and no dependencies are
updated in this change.
> build: Enable bzlmod

- browser/gui/app.cpp
- engine/engine.cpp
- engine/engine.h
- layout/layout.cpp
- layout/layout.h
- layout/layout_test.cpp
- style/unresolved_value.h
This is in use on e.g. https://bazel.build
> layout: Support % height on the root node

- .bazelrc
- .github/workflows/ci.yaml
This both allows us to see detailed timing information from the builds and gives us a remote cache.
When using one of the buildbuddy configs, the build output starts with a line like `INFO: Streaming build results to: https://app.buildbuddy.io/invocation/7108bed1-5b77-4b61-8db2-c9d1a6b283d1`, where the link leads to the information for that build.
> ci: Set up buildbuddy

- css2/tokenizer.cpp
After 0f8f2faae72d4d12b49374c9a8bd7ed0174e1b3e this is always used.
> css2: Remove unnecessary [[maybe_unused]]

- browser/gui/app.cpp
- gfx/sfml_canvas.cpp
- render/render.cpp
- render/render.h
- render/render_test.cpp
This is still missing things like scaling, clamping to max-width, and support for any image types other than .png, but hey, it works.
> We `<img>` now

- MODULE.bazel
- dom/dom.cpp
- dom/dom.h
- dom/dom_test.cpp
- style/BUILD
- style/style.cpp
- style/style_bench.cpp
- third_party/nanobench.BUILD
Before:
```
|               ns/op |                op/s |    err% |     total | is_match: class
|--------------------:|--------------------:|--------:|----------:|:----------------
|             1392.13 |           718322.70 |    1.2% |      0.01 | `match, few classes`
|             2272.80 |           439986.22 |    0.6% |      0.01 | `no match, few classes`
|             6605.88 |           151380.23 |    1.8% |      0.01 | `match, many classes`
|             5102.84 |           195969.17 |    0.2% |      0.01 | `no match, many classes`
```
After removing the bonus allocations:
```
|               ns/op |                op/s |    err% |     total | is_match: class
|--------------------:|--------------------:|--------:|----------:|:----------------
|              341.30 | …
```
> style: Get rid of allocations in class selector matching

- html2/iparser_actions.h
- html2/parser_states.cpp
- html2/parser_states_test.cpp
This brings the `time ./bazel-bin/browser/gui/gui --exit-after-load https://w.on-t.work/usable-web/` from 0m3.166s to 0m1.341s (real.)
Also, rendering https://w.on-t.work/usable-web/ works way better (but it still doesn't look good.)
Before:
(Yeah, it just ends at "General")
After:
So things work way better, but there are a few sizing issues to resolve before it's usable.
> html2: Parse </li> more correctly

- engine/engine.cpp
- engine/engine_test.cpp
This fixes google.com not being able to find its CSS variables.
> engine: Load stylesheets wherever they appear

- img/png.cpp
This fixes image-rendering issues on e.g. http://www.libpng.org/pub/png/pngpic2.html and https://gr.ht/2019/07/14/informed-consent.html
Before:
After:
> img/png: Support interlaced pngs

- html2/parser_states.cpp
- html2/parser_states_test.cpp
This fixes lots of "right drift" issues on e.g. http://www.libpng.org/pub/png/pngpic2.html.
Before:
After:
> html2: Handle more closing tag special cases

- img/png.cpp
This was hitting asserts in the rendering code as we currently assume that all pixel data in images is rgba.
The image responsible for blowing things up was https://s3.tosdr.org/logos/158.png, found on https://tosdr.org/en.
> img/png: Expand grayscale to rgba

- dom/dom.cpp
- dom/dom.h
- dom/dom_test.cpp
This is more compact and just generally nicer than my old ad-hoc format. It's also a bit of preparation for running the tree-construction html5lib-tests against our spec-compliant html parser.
> dom: Print nodes in the format used in the html5lib tests

- MODULE.bazel
- url/BUILD
- url/wpt_test.cpp
The test case we were hacking around (because it didn't belong in the test suite we were running) was moved into a separate thing in `https://github.com/web-platform-tests/wpt/commit/2b9af57f5f61e06e93a0caff5256d2c435b5c468`.
Also, downloading wpt like this should make our Windows CI a lot happier, looking at recent runs:
> url/test: Don't let the JSON parser patch the test input

- .github/workflows/ci.yaml
While this does speed up CI *a lot* and gives lovely build timing information, I need to work out how we want to deal with reads/writes to the buildbuddy cache from forks and how we manage the mandatory API keys.
@Zer0-One this should resolve the issues you saw in https://github.com/robinlinden/hastur/actions/runs/13147361339.
> ci: Only use buildbuddy if an API key is available

- .bazelrc
Previously, you'd get the Windows or macOS flags by default and have to manually pass `--noenable_platform_specific_config --config=linux` for things to work.
> build: Make cross-compilation on macOS/Windows hosts easier

- css/media_query.h
- css/media_query_test.cpp
- style/styled_node.cpp
This adds support for `prefers-reduced-motion: reduce` and things like `max-width: 30em`.
Both of these things are in use on e.g. https://snarkynomad.com.
> css: Support `prefers-reduced-motion` and em-units in media queries

- layout/layout.cpp
- layout/layout_test.cpp
This makes https://tosdr.org/en usable.
Before:
After:
I didn't take any screenshots with the images enabled until afterwards, and I'm too lazy to go back and redo my beautiful screenshots, but here's an after w/ images enabled:
> layout: Treat unresolvable %-heights as 'auto'

- .github/workflows/ci.yaml
The tokenless upload setup was apparently redone in codecov-cli 0.9.0,
so there's a chance a non-ancient version will work in forks now.
> ci: Update codecov-cli

- browser/gui/BUILD
- browser/gui/app.cpp
- browser/gui/app.h
> browser/gui: Hook up jpeg support

- browser/gui/app.cpp
- css/style_sheet.cpp
- css/style_sheet.h
- css/style_sheet_test.cpp
browser/gui/app.cpp is getting big, and this feels more at home in //css.
> css: Steal to_string(StyleSheet) from browser/gui

- MODULE.bazel
The freedesktop GitLab instance has pretty frequent downtime, and now there's 'up to a week' of downtime planned for the 16th of March.
See: https://gitlab.freedesktop.org/freedesktop/freedesktop/-/issues/2076
> deps: Add mirrors for all freedesktop dependencies

- archive/zlib.cpp
- archive/zlib.h
- archive/zlib_test.cpp
This was supported in both brotli and zstd, but not for the zlib decoder. :(
> archive/zlib: Allow limiting the output size

- .bazelrc
As far as I can tell, these are already the defaults in the version of Bazel we're targeting, but they probably recommend these settings for a reason.
> build: Apply buildbuddy suggestions to the remote cache setup

- .github/workflows/ci.yaml
CI occasionally fails w/
```
[2025-03-06 18:57:02.357] [I] Navigating to http://localhost:12345/example.html
[2025-03-06 18:57:06.383] [E] Error loading "http://localhost:12345/example.html": Unresolved
```
Hopefully this fixes that.
> ci: Make waiting for the test server more reliable

- gfx/canvas_command_saver.h
- gfx/canvas_command_saver_test.cpp
- gfx/gfx_example.cpp
- gfx/icanvas.h
- gfx/opengl_canvas.cpp
- gfx/opengl_canvas.h
- gfx/sfml_canvas.cpp
- gfx/sfml_canvas.h
- render/render.cpp
- render/render_test.cpp
This was literally the only place in the codebase where we still used
fill_rect, and draw_rect can do everything fill_rect can, so no point in
keeping it like this.
> render: Switch to draw_rect for drawing rects in the debug painting

- img/png.cpp
^ this image was responsible for triggering an assertion failure when I was trying to read w3 specs. :(
> img/png: Fix assertion failure when fed 16-bitdepth images

- css/media_query.h
- css/media_query_test.cpp
This is in use on e.g. https://github.com.
> css: Handle the rem unit in media queries

- json/BUILD
- json/json.h
- json/json_test.cpp
This isn't perfect, but it's a lot better than only getting a nullopt back. More granular error codes, as well as row:col-info can be added later.
> json: Improve error reporting

- css/media_query.h
- css/media_query_test.cpp
- engine/engine.cpp
These are in use on https://www.onlyscans.com/. That website is still unusable in hastur due to missing support for CSS variables inside functions like `rgba()` though.
> css: Support hover and orientation media queries

- css2/tokenizer.cpp
- css2/tokenizer.h
- css2/tokenizer_test.cpp
This also simplifies the tokenizer by not having any states aside from what used to be the "main" state. This was mostly so that it was easier to compare things to the spec when checking that things look correct, but it also both removes a lot of code and flattens what's left.
> css2: Fix invalid escapes being allowed if not first in idents

- .gitlint
- MODULE.bazel
- url/percent_encode.h
- url/url.cpp
Both commits are simple changes to comply w/ the newer spec versions. The spec changes are linked in the corresponding commits.
> url: Update parsing to work w/ newer wpt

- css/parser.cpp
- protocol/http.cpp
- style/style.cpp
- style/styled_node.cpp
- util/string.h
- util/string_test.cpp
The only place we used a multi-char delimiter was in a unit test, so no real need to support that use-case.
> util/string: Switch split_once to take a char delimiter

- layout/layout.cpp
- layout/layout_box.h
- layout/layout_box_test.cpp
- layout/layout_test.cpp
- style/styled_node.h
- style/styled_node_test.cpp
Due to the way the parent ptr is found, LayoutBox::get_property now
requires that the parent ptrs in the style tree are correctly set.
> layout: Make property accesses for anon blocks nicer

- layout/layout.cpp
- render/render.cpp
- render/render_test.cpp
The assertion failure is because we don't have any image scaling in place, and we only handle image sizes when doing inline layouts currently, so `display: block` on an `<img>`-tag can lead to the number of image bytes not matching what we need.
This assertion failure could be triggered in the wild on e.g. https://formspree.io/.
> render: Work around image px-count/layout-size mismatch

- dom/dom.cpp
- dom/dom_test.cpp
Before:
```
#document
| <!DOCTYPE html5>
| <html>
|   <head>
|   <body>
|     <title>
|     "goodbye"
|       "hello"
```
After:
```
#document
| <!DOCTYPE html5>
| <html>
|   <head>
|     <title>
|       "hello"
|   <body>
|     "goodbye"
```
> dom: Fix dom nodes being printed in the wrong order

- MODULE.bazel
- third_party/freetype2.BUILD
- third_party/libpng.BUILD
I ran into these issues when messing around with tooling for generating things from the Bazel query proto output. Not sure why the build doesn't hit them.
> Uninteresting dependency fixes

- browser/gui/app.cpp
- engine/engine.cpp
- protocol/http.cpp
- protocol/http.h
- protocol/http_test.cpp
- protocol/response.cpp
- protocol/response.h
- protocol/response_test.cpp
This is often used for e.g. `Set-Cookie`, and this is work towards getting cookies working.
> protocol: Support multiple http headers w/ the same key

- etest/etest2.cpp
- etest/etest2.h
- etest/test_name_filter_test.cpp
With this, e.g. patching html2/tokenizer_test.cpp's `s.run()` into 
```cpp
return s.run({
.test_name_filter = "^before",
});
```
will lead to running the test giving the output
```
206 test(s) registered.
Running 4 tests with the seed 727136149.
before attribute name: missing value: PASSED
before doctype name, unexpected null: PASSED
before attribute name: =            : PASSED
before doctype name, eof            : PASSED
```
or w/ the pattern `"before"`:
```
206 test(s) registered.
Running 13 tests with the seed 3650204568.
doctype before system identifier, missing identifier             : PASSED
before doctype name, unexpected null                             : PASSED
doctype before system identifier, double-quoted system identifier: PASSED
doctype system keyword, missing quote before …
```
> etest: Support filtering what tests to run

- MODULE.bazel
- idna/idna_data_processor.cpp
- idna/uts46.cpp
- idna/uts46_test.cpp
No exciting changes in tr44, just some changes in the input data: https://www.unicode.org/reports/tr44/#Change_History
tr46 has completely dropped IDNA2003 starting w/ Unicode 16, so that was nuked: https://www.unicode.org/reports/tr46/#IDNAComparison
> Target Unicode 16

- js/tokenizer.h
- js/tokenizer_test.cpp
I'm experimenting w/ hooking the work-in-progress JS bits up to the rest of the browser, and that means we can't assume trusted input anymore.
> js: Replace assert w/ real error-handling

- url/wpt_test.cpp
The failure flag only indicates if 'input' relative to 'base' is allowed to fail.
> url/test: Fix base url being allowed to fail if failure flag is set

- css/media_query.h
The rest of the file is stuck being non-constexpr due to us still supporting Clang 17 (via the zig cc stuff) and Clang 18.
> css: Make more of the media query code constexpr-enabled

- .bazelrc
- .github/workflows/ci.yaml
- MODULE.bazel
This downloads and uses a full LLVM setup to keep things as reproducible as possible, similar to our zig cross-compilation setup, but without going via the zig cc stuff.
> build: Add a hermetic llvm --config

- url/url.h
- url/url_test.cpp
A bunch of the C++ stdlib supports to_string(Type), as do a lot of our types, and it's what we support for printing types in //etest, so this makes things more convenient.
> url: Add to_string(Url) and to_string(ValidationError)

- browser/gui/app.cpp
- browser/gui/app.h
- engine/BUILD
- engine/engine.cpp
- engine/engine.h
- engine/engine_test.cpp
This doesn't run JS yet, but I'll open a PR for those parts soon. This is enough to make it easy to see what's needed for the tokenizer to work on websites we're testing against.
I might break things apart a bit later to allow the option of using a not-nih JS engine, but that's not really in scope while we're still getting all the basics set up.
```
[2025-06-01 19:54:58.344] [W] Failed to tokenize JavaScript in <script> tag:
document.querySelectorAll("a").forEach((link) => {
link.addEventListener("mouseover", (ev) => {
if (link.className == "vid") {
document.querySelector("#img").src = "";
document.querySelector("#video").src = link.href;
document.querySelector("#video").style.display = "revert";
} else {
document.querySelector("#img").src = link.href; …
```
> engine: Hook up the JS tokenizer

- .pre-commit-config.yaml
- MODULE.bazel
- README.md
- third_party/hermetic_cc_toolchain/zig-14.patch
This was the last place we had LLVM 17, so this unblocks cool new
things.
> deps/hermetic_cc_toolchain: Update to zig 14 (with llvm 19)

- MODULE.bazel
The 2025-06-26b release has been deleted from re2's GitHub.
See: https://github.com/google/re2/issues/550
> deps: Revert to an older version of re2

- html2/tokenizer_fuzz_test.cpp
- html2/tokenizer_test.cpp
The tokenizer always ends with this, and every test checks for it, so
let's make checking for it implicit.
> html2/test: Make eof token checking implicit

- gfx/sfml_canvas.cpp
This stopped being required in SFML 3.
> gfx/sfml: Don't heap-allocate the shader code

- .gitlint
- css/BUILD
- css/default.cpp
- gfx/BUILD
- gfx/opengl_canvas.cpp
- gfx/sfml_canvas.cpp
- img/BUILD
- img/jpeg_turbo_test.cpp
- img/png_test.cpp
- tool/BUILD
- tool/embed.cpp
This will go away once we target compilers w/ support for `#embed`, but
I feel this is a decent intermediate step as this is very little code,
allows us to treat the resources as compile-time constants instead of
mutable data, and doesn't require any namespace hacks where we include
the resources.
There's some issue w/ compiling the font embed file in MSVC in CI (without any output), but I can't reproduce it locally. Leaving that one as xxd while I investigate.
> tool: Set up a tool for embedding resources in a nicer-than-xxd way

- js/parser.h
- js/parser_test.cpp
This isn't reachable in the browser as the parser isn't ready to be deployed yet.
> js: Fix possible out-of-bounds read when parsing call expressions

- html2/parser_states.cpp
- html2/parser_states_test.cpp
I'm going to redesign this parser. This current-insertion-mode thing keeps causing trouble.
> html2: Fix missing mode overrides triggering an assert

- dom/dom.cpp
- dom/dom.h
- dom/dom_test.cpp
- html/BUILD
- html/html5lib_tree_construction_test.cpp
- html/parser.h
- html/parser_actions.h
- html/parser_options.h
- html2/iparser_actions.h
- html2/parser_states.cpp
- html2/parser_states_test.cpp
This allows us to run more of the spectests without hacking in comment exclusion stuff in our test runner. //style and //layout might need some work to support comments, so this is an default-off option for now.
> dom: Support keeping comments around

- .bazelrc
When we specify a hermetic toolchain we don't want Bazel to even try to find a host toolchain.
> build: Don't try to detect a host toolchain when not needed

- css/property_id.cpp
- layout/layout.cpp
- layout/layout_box_test.cpp
- layout/layout_test.cpp
- style/styled_node.cpp
- style/styled_node.h
- style/styled_node_test.cpp
https://gr.ht, after and before these changes:
https://seirdy.one, after and before these changes:
> layout: Take line-height into account when layouting text

- MODULE.bazel
- third_party/fmt.BUILD
- third_party/vulkan_hpp.BUILD
* fmt improved their wasm support and no longer requires manually
setting defines.
* vulkan_hpp stopped defining VULKAN_HPP_DISPATCH_LOADER_DYNAMIC in the
DispatchLoaderDynamic test.
> deps: Update dependencies

- style/styled_node.cpp
- style/styled_node_test.cpp
Very large font-size values lead to our sfml drawing code throwing a bad_alloc exception when trying to create fonts with silly sizes.
This issue was found w/ https://github.com/googleprojectzero/domato.
> style: Don't allow silly font-size values

- browser/gui/app.cpp
- browser/gui/app.h
- browser/gui/main.cpp
- browser/tui/tui.cpp
Tor Browser does less spoofing of its UA these days, so we may want to look into how we deal with ours at some point: https://blog.torproject.org/new-alpha-release-tor-browser-140a4/
> browser: Remove unused code, update the UA to match Tor Browser again

- idna/idna_data_processor.cpp
- layout/layout_test.cpp
- unicode/unicode_data_processor.cpp
This was mostly adding commas, removing `=` from `children = {`, and replacing create_element_node with just creating the nodes directly.
> layout/test: Enable clang-format for everything

- MODULE.bazel
This gets rid of 1 line of warning output per file compiled in the MSVC build.
> build: Silence warnings about overriding std:c++17 w/ std:c++latest
