robinlinden/hastur

etest/etest.cpp, etest/etest.h
See https://godbolt.org/z/4hnWoe for some examples.
=> etest: Print failed expects/requires if supported

.bazelrc, WORKSPACE
Upgrade the FTXUI version from patch 208 to patch 261.
There were no breaking change affecting hastur, since it was only using
the dom/ and screen/ subcomponent.
=> Upgrade FTXUI version.

LICENSE
This makes for a nicer default reading experience.
=> Wrap license at 80 cols

browser/tui.cpp, layout/layout.cpp, layout/layout.h, layout/layout_test.cpp
=> layout: Implement basic node placement 

layout/layout.cpp, layout/layout.h, layout/layout_test.cpp, style/BUILD, style/styled_node.cpp, style/styled_node.h, style/styled_node_test.cpp
=> Take padding into account when layouting

css/parser.h, css/parser_test.cpp
This PR adds support for parsing font size and family.
=> Initial support for expension of CSS font shorthand property

browser/gui/app.cpp, browser/gui/app.h, layout/layout.cpp, layout/layout.h, layout/layout_test.cpp, render/render.cpp
This gets rid of nearly all static_casts in hastur!
=> layout: Stop storing pixels in floats

browser/BUILD, browser/gui/app.cpp, browser/gui/app.h, gfx/BUILD, gfx/gfx.cpp, gfx/gfx.h, render/BUILD, render/render.cpp, render/render.h
Right now it's a bit boring, and there's only one implementation of it, but I'm sure we'll improve on it soon. :D
=> gfx: Add a new graphics abstraction

html2/tokenizer.cpp, html2/tokenizer.h
All the new tokenizer states are fully implemented.
=> Allow the html2::Tokenizer to tokenize example.com

WORKSPACE, util/BUILD, util/string.h
This PR adds the range-v3 library as a dependency. Unfortunately a patch is needed to be able to build the latest release of the library with clang13 and libc++. The patch is a commit from the master branch of the main repo.
Please object if you don't want that we add this dependency or if you have any concern with how the patching is handled.
=> Simplify no case compare

browser/engine.cpp, browser/gui/app.cpp, protocol/BUILD, protocol/http.cpp, protocol/http.h, protocol/http_test.cpp
Adds a class for handling headers from a http response. Value look up is case insensitive.
=> Add class for handling headers

dom2/document_type.h, dom2/document_type_test.cpp, dom2/element.h, dom2/element_test.cpp, html2/BUILD, html2/tree_builder.cpp, html2/tree_builder.h
This isn't enough to fully handle http://example.com yet, but it's enough to get us into the `<title>` element, and the diff was getting a bit big.
=> Start implementing spec-compliant tree construction

browser/gui/app.cpp, browser/gui/app.h
This isn't super useful without a few features still missing, but it makes my testing different pages a lot more convenient.
=> Follow links when clicked

WORKSPACE, third_party/vulkan.BUILD
Not in use yet, but will be used for a Vulkan GFX backend (not necessarily written by me) in the future!
Tested using this cute program:
```
#define VULKAN_HPP_DISPATCH_LOADER_DYNAMIC 1
#include "vulkan/vulkan.hpp"
VULKAN_HPP_DEFAULT_DISPATCH_LOADER_DYNAMIC_STORAGE
int main() {
vk::DynamicLoader dl;
PFN_vkGetInstanceProcAddr vkGetInstanceProcAddr =
dl.getProcAddress<PFN_vkGetInstanceProcAddr>("vkGetInstanceProcAddr");
VULKAN_HPP_DEFAULT_DISPATCHER.init(vkGetInstanceProcAddr);
vk::ApplicationInfo applicationInfo("test", 1, "vulkan magic", 1, VK_API_VERSION_1_1);
vk::InstanceCreateInfo instanceCreateInfo({}, &applicationInfo);
vk::Instance instance = vk::createInstance(instanceCreateInfo);
VULKAN_HPP_DEFAULT_DISPATCHER.init(instance);
instance.destroy();
}
```
=> deps: Add vulkan as a possible dependency

gfx/BUILD, gfx/gfx_example.cpp
@mkiael Do you think doing something like this is alright? It's pretty helpful when expanding the gfx API with e.g. text rendering. :P
=> gfx: Add a simple example application

html2/tokenizer.cpp, html2/tokenizer_test.cpp
I think we need to look into how the eof check is done to get the eof tokens emitted properly. Left two tests commented out until this has been fixed.
=> html2: Add support for parsing comments

browser/gui.cpp, browser/gui/app.cpp, browser/gui/app.h, geom/geom.h, geom/geom_test.cpp, gfx/gfx.cpp, gfx/gfx.h
I was having issues working on hastur on hidpi displays, and this is a decent step in the direction of proper support for anything but peasant resolutions. :P
=> Support (integer) scaling the entire application

.github/workflows/ci.yaml
This job was pretty special, so I moved it out from the matrix rather than adding lots of ifs to it.
Resolves #30
=> ci: Set up code coverage reporting using codecov.io

uri/uri.cpp, uri/uri_test.cpp
* Use .empty() instead of == "" to check for empty strings.
* Use if-init statements to reduce variable scope.
* Use 'c' instead of "c" for characters.
=> uri: Modernize code a bit

dom2/attr.h, dom2/cdata_section.h, dom2/character_data.h, dom2/comment.h, dom2/document.h, dom2/document_fragment.h, dom2/document_type.h, dom2/element.h, dom2/node.h, dom2/node_test.cpp, dom2/processing_instruction.h, dom2/text.h
This will be enforced by clang-tidy soon.
=> dom2: Add nodiscard and explicit where reasonable

html2/tokenizer.cpp, html2/tokenizer_test.cpp
=> html2: Add support for unquoted attribute values

gfx/BUILD, gfx/gfx_example.cpp, gfx/ipainter.h, gfx/opengl_painter.h, gfx/paint_command_saver.h, gfx/paint_command_saver_test.cpp, gfx/sfml_painter.cpp, gfx/sfml_painter.h, render/render.cpp
Let's say this completes the basic rendering setup and add separate issues for separate things to fix.
Resolves #26
=> Implement basic text rendering in the SFML gfx backend

browser/engine.h, browser/gui/app.cpp, css/default.css, layout/layout.cpp, layout/layout_test.cpp, render/render.cpp, style/style.cpp, style/style.h, style/style_test.cpp, style/styled_node.h, tui/tui.cpp
=> Style tree cleanup in preparation of css property inheritance

layout/layout.cpp, layout/layout_test.cpp
=> layout: Update calculations for width and margin to handle auto values

html2/tokenizer.cpp, html2/tokenizer.h, html2/tokenizer_test.cpp
@mkiael What do you think of something like this for support doing something with tokenizer errors?
=> html2: Set up infra for emitting tokenizer errors

style/style.cpp, style/style_test.cpp, style/styled_node.cpp, style/styled_node.h, style/styled_node_test.cpp
=> Add support for inheriting css properties

browser/engine.cpp, browser/gui.cpp, browser/gui/app.cpp
Nothing too exciting. Just random cleanup I did while working on other things.
=> browser: Update to more idiomatic C++

css/BUILD, css/rule.cpp, css/rule.h, css/rule_test.cpp
@robinlinden What do you think about having a widget for showing the stylesheet?
=> css: Add function for converting css::Rule to string

browser/BUILD, browser/engine.cpp, browser/engine.h, browser/gui/app.cpp, browser/gui/app.h
=> Stylesheet widget

.github/workflows/ci.yaml
Hopefully this makes it less crashy. If not, I'll open a PR retrying the clang-cl build a few times before giving up.
=> ci: Update clang-cl

WORKSPACE
See: https://github.com/ocornut/imgui/releases/tag/v1.88
=> deps: Update imgui

js/BUILD, js/ast.h, js/ast_test.cpp
This is very incomplete, but what do you think, @mkiael?
=> js: Set up a new library with a basic executable JS AST

WORKSPACE
See: https://github.com/ericniebler/range-v3/releases/tag/0.12.0
=> deps: Update range-v3

.github/workflows/ci.yaml, gfx/BUILD, gfx/basic_shader.vert, gfx/border_shader.frag, gfx/sfml_canvas.cpp
We talked about how to yoink the shaders out of the .cpp-file, and I gave one of the methods a try. :P What do you think? @mkiael 
The file endings I went with are from https://www.khronos.org/opengles/sdk/tools/Reference-Compiler/
=> gfx: Give the shaders their own files to live in

html2/tokenizer.cpp, protocol/response.cpp, render/render.cpp, uri/BUILD, uri/uri.cpp, uri/uri_test.cpp, util/string.h, util/string_test.cpp
=> uri: Add normalization of casing of the scheme and host

WORKSPACE
https://github.com/fmtlib/fmt/releases/tag/9.1.0
https://github.com/bazelbuild/platforms/releases/tag/0.0.6
=> deps: Update dependencies

style/styled_node.cpp, style/styled_node_test.cpp
This will be filled out with all other properties as soon as I've implemented handling of them in the rendering and layouting so I don't break everything that's working right now.
=> style: Set up infrastructure for initial values of properties

layout/layout.cpp, layout/layout_test.cpp
This is needed to not break things when merging the PR setting up the initial property values as the initial value for `font-size` is `medium`.
=> layout: Support the font-size absolute value keywords

css/parser_test.cpp, css2/tokenizer_test.cpp, etest/etest.cpp, etest/etest.h, html2/tokenizer_test.cpp
=> etest: Support custom assertion failure messages

css2/BUILD, css2/tokenizer.cpp, css2/tokenizer.h, css2/tokenizer_test.cpp
Support for escaped characters are still missing.
=> css2: Add initial support for ident token

WORKSPACE
https://github.com/madler/zlib/releases/tag/v1.2.13
=> deps: Update zlib

util/BUILD, util/base_parser.h, util/string.h
This is preparation for a new URL parser.
=> Add more utility functions to string.h

.bazelrc, WORKSPACE, browser/gui/app.cpp
imgui contained a breaking change that required a newer version of imgui-sfml.
=> deps: Update imgui and imgui-sfml

util/BUILD, util/uuid.h, util/uuid_test.cpp
This is preparation for Blob/Object URL generation
=> util/uuid: Add new_uuid function

layout/layout.cpp, layout/layout_test.cpp
With this change, it looks a lot more websites that we can render are also somewhat browsable.
=> layout: Handle text height more correctly if text contains newlines

.github/workflows/ci.yaml, .gitlint
=> ci: Set up gitlint to enforce the commit message format we're using

browser/gui/app.cpp
If the html or body element has a non-transparent background set, that should be used as the canvas background and not just as the element background.
This is currently done in hacky way outside of //render right now as doing correctly, not painting over things outside of the web page, without hacks in //render will require //gfx functionality not in place yet.
Before, html background ending where the html element ends:
After, html background filling the entire canvas:
=> browser/gui: Handle CSS special backgrounds

.github/workflows/ci.yaml
https://github.com/prettier/prettier/releases/tag/2.8.3
https://github.com/codecov/uploader/releases/tag/v0.3.2
=> Pin the codecov uploader

css/parser.h, css/parser_test.cpp
=> css: Expand the border and border-<side> shorthand properties

css/parser.h, css/parser_test.cpp
=> css: Handle border-radius w/ separate horizontal and vertical radii

.github/workflows/ci.yaml
https://github.com/jorisroovers/gitlint/releases/tag/v0.19.0
=> ci: Update gitlint

gfx/color.h, gfx/color_test.cpp
=> gfx: Implement creating Color from hsl/a values

util/crc32.h, util/crc32_test.cpp
I need this for some of the parsing bits I'm working on. :P
=> util: Add a helper for generating crc32 checksums

browser/gui/app.cpp, engine/engine.cpp, html2/tokenizer.cpp, layout/layout.cpp, style/style.cpp
Instead of first asking (std::holds_alternative) and then getting (std::get) the thing we want, we can try to get a ptr to it (std::get_if).
=> all: Simplify trying to get values out of std::variants

WORKSPACE
https://github.com/abseil/abseil-cpp/releases/tag/20230125.2
https://github.com/ocornut/imgui/releases/tag/v1.89.5
=> deps: Update abseil and imgui

layout/layout.cpp, layout/layout_test.cpp
This is still extremely incorrect, but slightly less so than before. :P
=> layout: Layout inline elements left-to-right instead of top-to-bottom

.github/workflows/ci.yaml
This is a hack and will be removed once a better option is available.
=> ci: Trick Bazel into detecting MSVC

.github/workflows/ci.yaml
https://prettier.io/blog/2023/07/05/3.0.0.html
=> ci: Update prettier

url/url.cpp, url/url.h, url/url_test.cpp
The first commit fixes a bug, the second commit adds URL serialization.
=> Add URL serialization

js/ast.h, js/tokenizer.h, js/tokenizer_test.cpp
It currently barely handles anything, but it's a start.
=> js: Implement a basic tokenizer

.github/FUNDING.yml
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository
=> meta: Add GitHub sponsor notice

css/property_id.cpp, css/property_id.h, style/styled_node.cpp, style/styled_node.h, style/styled_node_test.cpp
This will be used to decide what kind of whitespace-collapsing to do when.
=> css: Add the white-space property

WORKSPACE
https://github.com/SFML/imgui-sfml/releases/tag/v2.6
=> deps: Update boringssl and imgui-sfml

WORKSPACE
https://github.com/fmtlib/fmt/releases/tag/10.1.1
https://github.com/ArthurSonzogni/FTXUI/releases/tag/v5.0.0
=> deps: Update fmt, ftxui, and vulkan

WORKSPACE, third_party/simdjson.BUILD, url/BUILD, url/url.cpp, url/url_test.cpp, util/string.h
Also fixes the bugs that the tests uncovered.
=> url: Implement WPT url tests

gfx/sfml_canvas.cpp
Previously we were using the first font found, regardless of whether it loaded or not.
=> gfx/sfml: Use the first font that loads as a fallback

.bazelrc, .github/workflows/ci.yaml, WORKSPACE, third_party/libpng.BUILD
Originally I was just going to open an issue about it, but then I figured I'd check how feasible it is to add the good-first-issue tag, and I ended up doing it myself. :(
A pleasant bonus of using the zig-cc stuff for this is that we also test everything with musl libc and can cross-compile between all platforms relatively easily (pretty sure, not yet tested these things on Windows.)
Resolves #712
=> Add an aarch64 CI job

.bazelrc
See: https://github.com/google/sanitizers/wiki/AddressSanitizerOneDefinitionRuleViolation
=> build: Enable asan's ODR-violation detection

net/socket_test.cpp
Once in a hundred or so test runs on GitHub Actions, a detached thread would still be running when the test exited, and valgrind would report a few hundred bytes of possibly lost memory. This can be reproduced locally by adding a sleep at the end of the server thread to keep it alive until the test exits.
```
FAIL: //net:socket_test (see
/home/runner/.cache/bazel/_bazel_runner/a9f0723b1e9e47cd91eaa9d5188be59d/execroot/__main__/bazel-out/k8-fastbuild/testlogs/net/socket_test/test.log)
INFO: From Testing //net:socket_test:
==================== Test output for //net:socket_test:
==11== Memcheck, a memory error detector
==11== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==11== Using Valgrind-3.18.1 and LibVEX; rerun with -h for copyright info
==11== Command: …
```
=> net: Fix test flaky under valgrind by waiting for server thread to join

browser/gui/app.cpp, engine/engine.cpp, engine/engine.h, engine/engine_test.cpp, layout/layout.cpp, layout/layout.h, layout/layout_box_test.cpp, layout/layout_test.cpp
=> layout: Implement simple text wrapping of text runs in block elements

css/property_id.cpp, gfx/color.cpp, html2/tokenizer.cpp, html2/tokenizer_test.cpp, layout/layout.cpp, protocol/multi_protocol_handler.h, style/style.cpp, style/styled_node.cpp
Looking things up once is better than looking them up twice.
=> all: Replace container.contains + container.at w/ container.find

.clang-format, .github/workflows/ci.yaml, .pre-commit-config.yaml
=> ci: Add pre-commit checks

.github/workflows/ci.yaml
=> ci: Make codecov fail on error

layout/layout_box.cpp, layout/unresolved_value_test.cpp, style/styled_node.cpp, style/styled_node_test.cpp
These are in use on e.g. suckless.org.
=> Handle ch/ex units

url/url.cpp, url/url.h, url/url_test.cpp, util/string.h, util/string_test.cpp
=> url: Perform RFC3986 normalization on serialization

layout/layout.cpp, layout/layout_test.cpp
These will be conditionally included once we start loading images.
=> layout: Include <img>-alt-texts in the layout

browser/gui/app.cpp, browser/gui/app.h, geom/geom.h, geom/geom_test.cpp, render/render.cpp, render/render.h, render/render_test.cpp
This brings performance from slideshow to pretty good on a lot of websites I tested.
=> render: Support culling elements outside the viewport

layout/layout.cpp
This is just shuffling code around with 0 change in functionality in preparation of image stuff.
=> Wrap the layout system in a class, and split layout by layout kind

css/parser.cpp, css/parser_test.cpp, css/rule.cpp, css/rule.h, css/rule_test.cpp
=> css: Parse and store custom properties

style/style.cpp, style/style.h, style/style_test.cpp, style/styled_node.cpp, style/styled_node.h, style/styled_node_test.cpp
=> style: Resolve CSS variables in simple cases

layout/layout.cpp
It was pretty unclear where `last_text_box` could be null and that `current` always was non-null.
=> layout: Clarify nullability in whitespace-collapsing

protocol/http.cpp, protocol/http_test.cpp
=> protocol/http: Include query-parameters in requests

style/styled_node.cpp, style/styled_node_test.cpp
=> style: Support css variables with fallback values

type/sfml.cpp
This issue can be seen on https://seirdy.one/
Before:
Note that the text box containing the nbsp-character has 0 width:
After:
=> type/sfml: Add a workaround for non-breaking space measurements being 0

style/style.cpp, style/style_test.cpp
=> style: Match classes attached to a specific element type

archive/zstd.cpp, archive/zstd_test.cpp
=> archive/zstd: Fix faulty position check

browser/gui/app.cpp, browser/gui/app.h
This is less complex, less code, and allows copying the text.
=> browser/gui: Replace debug widgets w/ widget for dumping to console

engine/engine_test.cpp, layout/layout.cpp, layout/layout_box.cpp, render/render.cpp, style/styled_node.cpp, style/styled_node.h, style/styled_node_test.cpp, tui/tui.cpp
This is work towards #764 and #732.
=> style: Restructure the display property to support more values

.bazelrc, .github/workflows/ci.yaml
We've been using this in the gcc-14 job for a few months without any issues now.
=> ci: Run Linux jobs on Ubuntu 24.04

.github/workflows/ci.yaml, WORKSPACE
boringssl builds again, even with 0 patches which is fantastic, but now imgui decided to break. :(
=> deps: Update boringssl, simdjson, and vulkan

layout/layout.cpp, style/styled_node.cpp, style/styled_node.h, style/unresolved_value.cpp, style/unresolved_value.h, style/unresolved_value_test.cpp
This is used for the `<footer>` on https://gr.ht/.
=> style: Support resolving the vw unit

protocol/file_handler_test.cpp, protocol/http.cpp, protocol/http_test.cpp, protocol/multi_protocol_handler_test.cpp, protocol/response_test.cpp
There's a few other commits in here, but they're all adding more tests and things like that.
=> protocol/http: Keep ports if the scheme isn't recognized

.github/workflows/ci.yaml, WORKSPACE
The changelog for standalone asio is no longer updated, but the changes can be found in the boost one: https://www.boost.org/doc/libs/1_86_0/doc/html/boost_asio/history.html
=> deps: Update asio, imgui, stb, and vulkan

css/media_query.h, css/media_query_test.cpp
This fixes 2 `Unable to parse media query: 'screen and (min-width: 412px)'` warnings on https://gr.ht
=> css: Support 'and' in media queries

engine/engine.cpp, layout/BUILD, layout/layout.cpp, layout/layout.h, layout/layout_property_test.cpp, layout/layout_test.cpp
Part 1 of me finally getting around to merging my `<img>` branch.
=> layout: Hide the img alt-text if an image has been loaded

etest/etest2.cpp
=> etest: Print information about failing tests at the end of the test log

type/sfml.cpp
Instead of just looking at the first font with a name that might match, we try every font with a name that might match.
=> type/sfml: Try harder to find fonts

archive/BUILD, azm/BUILD, css/BUILD, css2/BUILD, dom/BUILD, etest/BUILD, gfx/BUILD, html/BUILD, html2/BUILD, idna/BUILD, img/BUILD, js/BUILD, layout/BUILD, net/BUILD, protocol/BUILD, style/BUILD, unicode/BUILD, util/BUILD, wasm/BUILD
This makes it a bit clearer what's intended.
=> build: Replace slicing w/ removesuffix where it makes sense

style/unresolved_value.cpp, style/unresolved_value_test.cpp
This is in use on e.g. https://0x3ccc.github.io/
=> style: Support resolving the vh unit

browser/gui/BUILD, browser/gui/app.cpp, browser/gui/app.h, engine/engine.cpp, engine/engine.h
This is hidden behind a keybind as it's only really useful to me while I'm hooking all the systems up.
=> browser/gui: Add infra around downloading images

.github/workflows/ci.yaml, render/render.cpp
There is a minor formatting difference between 18 and 19, and I keep having to avoid committing it.
=> ci: Update to clang-format 19

url/wpt_test.cpp
Looks like this has never been tested, but everything was perfect anyway, so that's nice. :P
=> url/test: Fix origin being ignored in the wpt test

protocol/in_memory_cache.h, protocol/in_memory_cache_test.cpp
The cache is used in a threaded context where we download things like
stylesheets and images in parallel. This threading will go away once
we've switched to async-io for downloading resources.
=> protocol: Fix InMemoryCache not being thread-safe

protocol/file_handler.cpp, protocol/file_handler_test.cpp
This lacks styling, not being quirky HTML, and all the fancy things you might want, but it's a start.
Resolves #840
=> protocol/file: Display a basic index when navigating to a folder

.github/workflows/ci.yaml, html/parser.h
We'll add a libc++ job as well, but there are some issues in SFML that needs sorting out before that's possible.
=> ci: Add an LLVM 20 + libstdc++ job

style/styled_node.cpp, style/styled_node_test.cpp
This fixes e.g. text colour issues on google.com.
=> style: Support variables as fallback values

layout/layout.cpp, layout/layout_test.cpp
This allow blocks nested in inlines to be as wide as the closest parent block, instead of being restricted to the width of the inline parent.
=> layout: Improve width calculation of blocks nested in inlines

idna/idna_data_processor.cpp
This adds sanity checks to code-point parsing, and brings the number of allocations reported by valgrind from 79,563 to 42,318 for a binary built w/ clang-18 + libc++-18.
=> idna: Reduce number of heap allocations in idna processing

wasm/leb128.h
`constexpr std::ceil` is part of C++23, but isn't implemented everywhere we need it yet. :(
=> wasm: run the 'remaining value bits'-check in leb128 at compile time

bzl/copts.bzl, dom/xpath.h, protocol/in_memory_cache.h, wasm/validation.cpp
See https://quuxplusone.github.io/blog/2022/10/07/wctad-maybe-unsupported/ for some info about pitfalls of CTAD.
=> build: Enable -Wctad-maybe-unsupported

css/media_query.h, css/media_query_test.cpp
=> css: Support 'height' media queries

html/parser.h, html/parser_actions.h, html/parser_test.cpp, html2/parser_states_test.cpp
This is work towards hooking up `<script>` support.
=> html: Add a element-closed callback

MODULE.bazel, gfx/BUILD, gfx/sfml_canvas.cpp, type/BUILD, type/fallback_font.cpp, type/fallback_font.h, type/sfml.cpp, type/sfml.h
We used to look really hard, and die if we couldn't find a font. Now there's always a font available.
There was no thought behind picking Open Sans over any other font, so we can switch to whatever's nice later.
=> Use an embedded fallback font

js/tokenizer.h, js/tokenizer_test.cpp
This is enough to tokenize the first script on https://likeadragonmaid.dev/.
Before:
```
<...>
[2025-06-05 17:56:02.559] [W] Failed to tokenize JavaScript in <script> tag:
function script() {
bd.style.background="black";
document.getElementById('footer').style.display = 'none';
}
document.getElementById('boring').onclick = function () {
script();
}
[2025-06-05 17:56:02.559] [W] Failed to tokenize JavaScript in <script> tag:
function changeBG() {
var bgNo = Math.floor(Math.random() * 56);
var bd = document.getElementsByTagName("body")[0];
bd.style.backgroundImage="url('assets/backgrounds/"+bgNo+".gif')";
}
document.getElementById('boring2').onclick = function () {
changeBG();
}
[2025-06-05 17:56:02.560] [W] Failed to tokenize JavaScript in <script> tag:
var bgNo = Math.floor(Math.random() …
```
=> js: Support tokenizing (simple) strings, braces, dots, and equal signs

css/parser.cpp, engine/engine_test.cpp, html2/parser_states.cpp
This is possible now that we no longer support libc++17.
=> Switch to std::ranges::contains where it makes sense

.github/workflows/ci.yaml, .pre-commit-config.yaml, MODULE.bazel
The check-shebang-scripts-are-executable thing would've caught f6850d550b099ea825ece97dc335642d4ac25ba3. :P
=> deps: Update Bazel rules, boringssl, imgui, and vulkan
